/* NINJA Basic (with Sonic Adventure DX additions) model
*
* Generated by SAMDL
*
*/

enum OBJ_SHAREOBJTexName
{
	OBJ_SHAREOBJTexName_eisei01,
	OBJ_SHAREOBJTexName_ref_red01,
	OBJ_SHAREOBJTexName_ref_crome,
	OBJ_SHAREOBJTexName_rocket01,
	OBJ_SHAREOBJTexName_rocket12,
	OBJ_SHAREOBJTexName_courseter03,
	OBJ_SHAREOBJTexName_courseter02,
	OBJ_SHAREOBJTexName_courseter08,
	OBJ_SHAREOBJTexName_rocket08,
	OBJ_SHAREOBJTexName_rocket11,
	OBJ_SHAREOBJTexName_saku01,
	OBJ_SHAREOBJTexName_st_slight01,
	OBJ_SHAREOBJTexName_hg01,
	OBJ_SHAREOBJTexName_am_tp058_64,
	OBJ_SHAREOBJTexName_am_tp061_64,
	OBJ_SHAREOBJTexName_am_tp060_64,
	OBJ_SHAREOBJTexName_am_tp055_64,
	OBJ_SHAREOBJTexName_am_tp056_64,
	OBJ_SHAREOBJTexName_am_tp047_64b,
	OBJ_SHAREOBJTexName_am_tp035_16,
	OBJ_SHAREOBJTexName_am_tp051_16,
	OBJ_SHAREOBJTexName_am_tp063_32,
	OBJ_SHAREOBJTexName_am_tp053_64,
	OBJ_SHAREOBJTexName_am_tp041_32,
	OBJ_SHAREOBJTexName_courseter15,
	OBJ_SHAREOBJTexName_am_tp032_32,
	OBJ_SHAREOBJTexName_am_tp048_32,
	OBJ_SHAREOBJTexName_am_tp037_32c,
	OBJ_SHAREOBJTexName_am_tp064_32,
	OBJ_SHAREOBJTexName_am_tp031_32,
	OBJ_SHAREOBJTexName_am_tp030_64,
	OBJ_SHAREOBJTexName_am_tp028_16,
	OBJ_SHAREOBJTexName_am_tp040_8,
	OBJ_SHAREOBJTexName_am_tp043_64,
	OBJ_SHAREOBJTexName_am_tp034_32,
	OBJ_SHAREOBJTexName_am_tp033_32,
	OBJ_SHAREOBJTexName_am_tp036_16,
	OBJ_SHAREOBJTexName_am_tp054_32,
	OBJ_SHAREOBJTexName_am_tp046_8,
	OBJ_SHAREOBJTexName_am_tp038_32,
	OBJ_SHAREOBJTexName_am_tp062_16,
	OBJ_SHAREOBJTexName_am_tp042_32,
	OBJ_SHAREOBJTexName_m16_tp1_001,
	OBJ_SHAREOBJTexName_m32_tp1_004,
	OBJ_SHAREOBJTexName_m32_tp1_003,
	OBJ_SHAREOBJTexName_m32_tp1_002,
	OBJ_SHAREOBJTexName_m32_tp1_007,
	OBJ_SHAREOBJTexName_m32_tp1_006,
	OBJ_SHAREOBJTexName_m32_tp1_005,
	OBJ_SHAREOBJTexName_m32_tp2_009,
	OBJ_SHAREOBJTexName_m32_tp2_004,
	OBJ_SHAREOBJTexName_courseter04,
	OBJ_SHAREOBJTexName_courseter06,
	OBJ_SHAREOBJTexName_am_tp044_16b,
	OBJ_SHAREOBJTexName_yubi,
	OBJ_SHAREOBJTexName_1,
	OBJ_SHAREOBJTexName_2,
	OBJ_SHAREOBJTexName_3,
	OBJ_SHAREOBJTexName_4,
	OBJ_SHAREOBJTexName_5,
	OBJ_SHAREOBJTexName_6,
	OBJ_SHAREOBJTexName_7,
	OBJ_SHAREOBJTexName_8,
	OBJ_SHAREOBJTexName_9,
	OBJ_SHAREOBJTexName_arm,
	OBJ_SHAREOBJTexName_arm0,
	OBJ_SHAREOBJTexName_arm1,
	OBJ_SHAREOBJTexName_bamp_l,
	OBJ_SHAREOBJTexName_black,
	OBJ_SHAREOBJTexName_black0,
	OBJ_SHAREOBJTexName_blue,
	OBJ_SHAREOBJTexName_board0,
	OBJ_SHAREOBJTexName_body1,
	OBJ_SHAREOBJTexName_buttom,
	OBJ_SHAREOBJTexName_console,
	OBJ_SHAREOBJTexName_cover,
	OBJ_SHAREOBJTexName_enjinecov,
	OBJ_SHAREOBJTexName_fan,
	OBJ_SHAREOBJTexName_grass,
	OBJ_SHAREOBJTexName_gray,
	OBJ_SHAREOBJTexName_green,
	OBJ_SHAREOBJTexName_hand0,
	OBJ_SHAREOBJTexName_hoho,
	OBJ_SHAREOBJTexName_kuti,
	OBJ_SHAREOBJTexName_kuti0,
	OBJ_SHAREOBJTexName_lblue,
	OBJ_SHAREOBJTexName_met,
	OBJ_SHAREOBJTexName_mimi,
	OBJ_SHAREOBJTexName_mimi0,
	OBJ_SHAREOBJTexName_mugen,
	OBJ_SHAREOBJTexName_orange,
	OBJ_SHAREOBJTexName_panel,
	OBJ_SHAREOBJTexName_pink,
	OBJ_SHAREOBJTexName_red,
	OBJ_SHAREOBJTexName_seat0,
	OBJ_SHAREOBJTexName_0
};

NJS_MATERIAL matlist_000F125C[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_SHAREOBJTexName_am_tp047_64b, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_SRC }
};

Sint16 poly_000F1270[] = {
	4, 3, 2, 1, 0,
	4, 7, 6, 5, 4,
	4, 11, 10, 9, 8
};

NJS_TEX uv_000F1290[] = {
	{ 0, 255 },
	{ 84, 1 },
	{ 255, 255 },
	{ 166, 1 },
	{ 0, 255 },
	{ 84, 1 },
	{ 255, 255 },
	{ 166, 1 },
	{ 0, 255 },
	{ 84, 1 },
	{ 255, 255 },
	{ 166, 1 }
};

NJS_MESHSET_SADX meshlist_000F12C0[] = {
	{ NJD_MESHSET_TRIMESH | 0, 3, poly_000F1270, NULL, NULL, NULL, uv_000F1290, NULL }
};

NJS_VECTOR vertex_000F12D8[] = {
	{ 1.873595f, -0.00003f, -3.245171f },
	{ 6.775995f, -67.68094f, -11.63937f },
	{ -1.873601f, -0.00003f, 3.245167f },
	{ -6.775991f, -67.68094f, 11.63937f },
	{ 1.873602f, -0.00003f, 3.245167f },
	{ 6.775995f, -67.68094f, 11.63937f },
	{ -1.873596f, -0.00003f, -3.245171f },
	{ -6.775995f, -67.68094f, -11.63937f },
	{ -3.747198f, -0.00003f, 0.000003f },
	{ -13.55199f, -67.68094f, -0.00001f },
	{ 3.747198f, -0.00003f, 0.000003f },
	{ 13.55199f, -67.68094f, -0.00001f }
};

NJS_VECTOR normal_000F1368[] = {
	{ -0.864219f, 0, -0.503115f },
	{ -0.864219f, 0, -0.503115f },
	{ -0.864219f, 0, -0.503115f },
	{ -0.864219f, 0, -0.503115f },
	{ 0.864219f, 0, -0.503115f },
	{ 0.864219f, 0, -0.503115f },
	{ 0.864219f, 0, -0.503115f },
	{ 0.864219f, 0, -0.503115f },
	{ 0, 0, 1 },
	{ 0, 0, 1 },
	{ 0, 0, 1 },
	{ 0, 0, 1 }
};

NJS_MODEL_SADX attach_000F13F8 = { vertex_000F12D8, normal_000F1368, LengthOfArray(vertex_000F12D8), meshlist_000F12C0, matlist_000F125C, LengthOfArray(meshlist_000F12C0), LengthOfArray(matlist_000F125C),{ 0, -33.84047f, 0 }, 36.2792f, NULL };

NJS_OBJECT object_000F1420 = { NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_000F13F8, 0, -18.98458f, 0, 0, 0, 0x2D8, 1, 1, 1, NULL, NULL };
