/* NINJA Basic (with Sonic Adventure DX additions) model
*
* Generated by SAMDL
*
*/

enum OBJ_RUINTexName
{
	OBJ_RUINTexName_ama_lw076,
	OBJ_RUINTexName_ama_h03,
	OBJ_RUINTexName_ama_lw001,
	OBJ_RUINTexName_ama_lw002,
	OBJ_RUINTexName_ama_lw003,
	OBJ_RUINTexName_ama_lw004,
	OBJ_RUINTexName_ama_lw005,
	OBJ_RUINTexName_ama_lw006,
	OBJ_RUINTexName_ama_lw007,
	OBJ_RUINTexName_ama_lw008,
	OBJ_RUINTexName_ama_lw009,
	OBJ_RUINTexName_ama_lw010,
	OBJ_RUINTexName_ama_lw011,
	OBJ_RUINTexName_ama_lw012,
	OBJ_RUINTexName_ama_lw013,
	OBJ_RUINTexName_ama_lw015,
	OBJ_RUINTexName_ama_lw016,
	OBJ_RUINTexName_ama_lw017,
	OBJ_RUINTexName_ama_lw018,
	OBJ_RUINTexName_ama_lw019,
	OBJ_RUINTexName_ama_lw020,
	OBJ_RUINTexName_ama_lw021,
	OBJ_RUINTexName_ama_lw022,
	OBJ_RUINTexName_ama_lw023,
	OBJ_RUINTexName_ama_lw024,
	OBJ_RUINTexName_ama_lw025,
	OBJ_RUINTexName_ama_lw026,
	OBJ_RUINTexName_ama_lw027,
	OBJ_RUINTexName_ama_lw028,
	OBJ_RUINTexName_ama_lw029,
	OBJ_RUINTexName_ama_lw030,
	OBJ_RUINTexName_ama_lw031,
	OBJ_RUINTexName_ama_lw032,
	OBJ_RUINTexName_ama_lw033,
	OBJ_RUINTexName_ama_lw034,
	OBJ_RUINTexName_ama_lw035,
	OBJ_RUINTexName_ama_lw036,
	OBJ_RUINTexName_ama_lw037,
	OBJ_RUINTexName_ama_lw038,
	OBJ_RUINTexName_ama_lw039,
	OBJ_RUINTexName_ama_lw040,
	OBJ_RUINTexName_ama_lw041,
	OBJ_RUINTexName_ama_lw042,
	OBJ_RUINTexName_ama_lw044,
	OBJ_RUINTexName_ama_lw045,
	OBJ_RUINTexName_ama_lw047,
	OBJ_RUINTexName_ama_lw048,
	OBJ_RUINTexName_ama_lw049,
	OBJ_RUINTexName_ama_lw050,
	OBJ_RUINTexName_ama_lw051,
	OBJ_RUINTexName_ama_lw052,
	OBJ_RUINTexName_ama_lw054,
	OBJ_RUINTexName_ama_lw055,
	OBJ_RUINTexName_ama_lw056,
	OBJ_RUINTexName_ama_lw057,
	OBJ_RUINTexName_ama_lw059,
	OBJ_RUINTexName_ama_lw062,
	OBJ_RUINTexName_ama_lw063,
	OBJ_RUINTexName_ama_lw064,
	OBJ_RUINTexName_ama_h01,
	OBJ_RUINTexName_honda_toge2,
	OBJ_RUINTexName_honda_turn,
	OBJ_RUINTexName_lost2_21,
	OBJ_RUINTexName_lost1_17,
	OBJ_RUINTexName_lost1_19,
	OBJ_RUINTexName_lost1_24,
	OBJ_RUINTexName_lost1_26,
	OBJ_RUINTexName_lost1_27,
	OBJ_RUINTexName_lost1_29,
	OBJ_RUINTexName_lost1_30,
	OBJ_RUINTexName_lost1_31,
	OBJ_RUINTexName_lost1_33,
	OBJ_RUINTexName_lost1_36,
	OBJ_RUINTexName_lost1_38,
	OBJ_RUINTexName_lost1_41,
	OBJ_RUINTexName_lost1_44,
	OBJ_RUINTexName_lost1_7,
	OBJ_RUINTexName_lost2_16,
	OBJ_RUINTexName_lost1_12,
	OBJ_RUINTexName_lost2_7,
	OBJ_RUINTexName_m64_los036,
	OBJ_RUINTexName_m128_los003,
	OBJ_RUINTexName_m128_los004,
	OBJ_RUINTexName_m128_los010,
	OBJ_RUINTexName_m128_los015,
	OBJ_RUINTexName_m128_los036,
	OBJ_RUINTexName_m128_los037,
	OBJ_RUINTexName_m128_los038,
	OBJ_RUINTexName_m128_los040,
	OBJ_RUINTexName_m128_los042,
	OBJ_RUINTexName_m128_los044,
	OBJ_RUINTexName_m32_los010,
	OBJ_RUINTexName_m32_los011,
	OBJ_RUINTexName_m32_los012,
	OBJ_RUINTexName_m32_los016,
	OBJ_RUINTexName_m64_fall1,
	OBJ_RUINTexName_m64_fall2,
	OBJ_RUINTexName_m64_los001,
	OBJ_RUINTexName_m64_los005,
	OBJ_RUINTexName_m64_los009,
	OBJ_RUINTexName_m64_los013,
	OBJ_RUINTexName_m64_los014,
	OBJ_RUINTexName_m64_los015,
	OBJ_RUINTexName_m64_los017,
	OBJ_RUINTexName_m64_los018,
	OBJ_RUINTexName_m64_los021,
	OBJ_RUINTexName_m64_los022,
	OBJ_RUINTexName_m64_los024,
	OBJ_RUINTexName_m64_los031,
	OBJ_RUINTexName_m64_los033,
	OBJ_RUINTexName_m64_los034,
	OBJ_RUINTexName_m64_los035,
	OBJ_RUINTexName_m128_los001,
	OBJ_RUINTexName_mizu1,
	OBJ_RUINTexName_vqm128_los019,
	OBJ_RUINTexName_vqlost1_11,
	OBJ_RUINTexName_vqlost1_14,
	OBJ_RUINTexName_vqlost1_22,
	OBJ_RUINTexName_vqlost1_37,
	OBJ_RUINTexName_vqlost1_39,
	OBJ_RUINTexName_vqlost1_43,
	OBJ_RUINTexName_vqm128_los018,
	OBJ_RUINTexName_vq32_los010,
	OBJ_RUINTexName_vq128_los042,
	OBJ_RUINTexName_vq64_los005,
	OBJ_RUINTexName_vq64_los013,
	OBJ_RUINTexName_vq64_los014
};

NJS_MATERIAL matlist_0012B558[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_29, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_24, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_vq128_los042, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_7, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_29, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_0012B5D0[] = {
	0x8000u | 6, 25, 27, 24, 26, 2, 0,
	4, 7, 6, 9, 8,
	4, 19, 18, 21, 20,
	4, 1, 0, 3, 2,
	4, 15, 14, 17, 16,
	4, 11, 10, 13, 12,
	4, 3, 25, 1, 27
};

Sint16 poly_0012B61A[] = {
	4, 3, 2, 5, 4,
	4, 23, 22, 25, 24,
	4, 9, 8, 11, 10,
	4, 17, 16, 19, 18
};

Sint16 poly_0012B642[] = {
	4, 5, 4, 7, 6,
	4, 21, 20, 23, 22,
	0x8000u | 8, 4, 6, 2, 12, 24, 14, 22, 20,
	0x8000u | 8, 23, 21, 25, 15, 3, 13, 5, 7
};

Sint16 poly_0012B67A[] = {
	4, 13, 12, 15, 14
};

Sint16 poly_0012B684[] = {
	4, 8, 6, 10, 12,
	4, 18, 16, 20, 14,
	4, 11, 13, 9, 7,
	4, 19, 21, 17, 15
};

Sint16 poly_0012B6AC[] = {
	4, 0, 1, 26, 27
};

NJS_TEX uv_0012B6B8[] = {
	{ 2550, 3 },
	{ 2550, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 3060, 3 },
	{ 3060, 255 },
	{ 0, 255 },
	{ 2550, 255 },
	{ 0, 3 },
	{ 2550, 3 },
	{ 2550, 3 },
	{ 0, 3 },
	{ 2550, 255 },
	{ 0, 255 },
	{ 0, 255 },
	{ 2550, 255 },
	{ 0, 3 },
	{ 2550, 3 },
	{ 0, 255 },
	{ 2550, 255 },
	{ 0, 3 },
	{ 2550, 3 },
	{ 2550, 3 },
	{ 0, 3 },
	{ 2550, 255 },
	{ 0, 255 },
	{ 3060, 3 },
	{ 0, 3 },
	{ 3060, 255 },
	{ 0, 255 }
};

NJS_TEX uv_0012B730[] = {
	{ 2550, 255 },
	{ 0, 255 },
	{ 2550, 3 },
	{ 0, 3 },
	{ 2550, 255 },
	{ 0, 255 },
	{ 2550, 3 },
	{ 0, 3 },
	{ 0, 3 },
	{ 2550, 3 },
	{ 0, 255 },
	{ 2550, 255 },
	{ 0, 3 },
	{ 2550, 3 },
	{ 0, 255 },
	{ 2550, 255 }
};

NJS_TEX uv_0012B770[] = {
	{ 0, 255 },
	{ 764, 255 },
	{ 0, 1 },
	{ 765, 1 },
	{ 765, 1 },
	{ 0, 1 },
	{ 764, 255 },
	{ 0, 255 },
	{ 0, 255 },
	{ 0, 1 },
	{ 76, 255 },
	{ 76, 1 },
	{ 1453, 255 },
	{ 1453, 1 },
	{ 1530, 255 },
	{ 1530, 1 },
	{ 0, 254 },
	{ 0, 1 },
	{ 76, 254 },
	{ 76, 1 },
	{ 1453, 254 },
	{ 1453, 1 },
	{ 1529, 254 },
	{ 1529, 1 }
};

NJS_TEX uv_0012B7D0[] = {
	{ 0, 255 },
	{ 765, 255 },
	{ 0, -1274 },
	{ 765, -1274 }
};

NJS_TEX uv_0012B7E0[] = {
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 255 },
	{ 0, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 }
};

NJS_TEX uv_0012B820[] = {
	{ 0, 255 },
	{ 765, 255 },
	{ 0, -1274 },
	{ 765, -1274 }
};

NJS_MESHSET_SADX meshlist_0012B830[] = {
	{ NJD_MESHSET_TRIMESH | 0, 7, poly_0012B5D0, NULL, NULL, NULL, uv_0012B6B8, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 4, poly_0012B61A, NULL, NULL, NULL, uv_0012B730, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 4, poly_0012B642, NULL, NULL, NULL, uv_0012B770, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 1, poly_0012B67A, NULL, NULL, NULL, uv_0012B7D0, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 4, poly_0012B684, NULL, NULL, NULL, uv_0012B7E0, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 1, poly_0012B6AC, NULL, NULL, NULL, uv_0012B820, NULL }
};

NJS_VECTOR vertex_0012B8C0[] = {
	{ -44.07388f, 0, 38.71437f },
	{ -44.07388f, 0.000003f, -38.71444f },
	{ -44.07388f, 5, 38.71437f },
	{ -44.07388f, 5.000003f, -38.71444f },
	{ -49.07388f, 5, 39.20682f },
	{ -49.07388f, 5.000003f, -39.20689f },
	{ -49.07388f, 20, 39.20682f },
	{ -49.07388f, 20, -39.20689f },
	{ -49.07388f, 25, 39.20682f },
	{ -49.07388f, 25, -39.20689f },
	{ -44.07388f, 25, 38.71437f },
	{ -44.07388f, 25, -38.71444f },
	{ -44.07388f, 20, 38.71437f },
	{ -44.07388f, 20, -38.71444f },
	{ 45.92612f, 20, 29.85015f },
	{ 45.92612f, 20, -29.85019f },
	{ 45.92612f, 25, 29.85015f },
	{ 45.92612f, 25, -29.85019f },
	{ 50.92612f, 25, 29.35769f },
	{ 50.92612f, 25, -29.35773f },
	{ 50.92612f, 20, 29.35769f },
	{ 50.92612f, 20, -29.35773f },
	{ 50.92612f, 5, 29.35769f },
	{ 50.92612f, 5.000002f, -29.35773f },
	{ 45.92612f, 5, 29.85015f },
	{ 45.92612f, 5.000002f, -29.85019f },
	{ 45.92612f, 0, 29.85015f },
	{ 45.92612f, 0.000002f, -29.85019f }
};

NJS_VECTOR normal_0012BA10[] = {
	{ -0.550679f, -0.572363f, 0.6075799f },
	{ -0.550679f, -0.572363f, -0.6075799f },
	{ -0.217439f, -0.327259f, 0.9195769f },
	{ -0.217438f, -0.327259f, -0.9195769f },
	{ -0.550679f, -0.572363f, 0.6075799f },
	{ -0.550679f, -0.572363f, -0.6075799f },
	{ -0.671559f, 0, 0.7409509f },
	{ -0.671559f, 0, -0.7409509f },
	{ -0.550679f, 0.572363f, 0.6075799f },
	{ -0.550679f, 0.572363f, -0.6075799f },
	{ 0.602167f, 0.582689f, 0.545773f },
	{ 0.602167f, 0.582689f, -0.545773f },
	{ 0.382143f, 0.276851f, 0.881658f },
	{ 0.382143f, 0.276851f, -0.881658f },
	{ -0.217438f, 0.327259f, 0.9195769f },
	{ -0.217438f, 0.327259f, -0.9195769f },
	{ -0.550679f, 0.572363f, 0.6075799f },
	{ -0.550679f, 0.572363f, -0.6075799f },
	{ 0.602167f, 0.582689f, 0.545773f },
	{ 0.602167f, 0.582689f, -0.545773f },
	{ 0.7409509f, 0, 0.671559f },
	{ 0.7409509f, 0, -0.671559f },
	{ 0.602167f, -0.582689f, 0.545773f },
	{ 0.602167f, -0.582689f, -0.545773f },
	{ 0.382143f, -0.276851f, 0.8816569f },
	{ 0.382144f, -0.276851f, -0.8816569f },
	{ 0.602167f, -0.582689f, 0.545773f },
	{ 0.602167f, -0.582689f, -0.545773f }
};

NJS_MODEL_SADX attach_0012BB60 = { vertex_0012B8C0, normal_0012BA10, LengthOfArray(vertex_0012B8C0), meshlist_0012B830, matlist_0012B558, LengthOfArray(meshlist_0012B830), LengthOfArray(matlist_0012B558),{ 0.9261169f, 12.5f, -0.00034f }, 63.53879f, NULL };

NJS_OBJECT object_0012BB88 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_0012BB60, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Ashiba02


NJS_MATERIAL matlist_0012BBBC[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_29, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_vq128_los042, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_24, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_vq128_los042, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_29, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_7, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_0012BC48[] = {
	4, 23, 2, 22, 0
};

Sint16 poly_0012BC52[] = {
	4, 2, 3, 0, 1,
	4, 7, 3, 23, 2,
	4, 15, 11, 14, 10,
	4, 13, 17, 12, 16,
	4, 27, 19, 26, 18,
	4, 21, 25, 20, 24,
	6, 7, 23, 5, 22, 1, 0
};

Sint16 poly_0012BC9C[] = {
	0x8000u | 8, 9, 13, 3, 25, 7, 27, 6, 11,
	8, 8, 12, 1, 24, 5, 26, 4, 10
};

Sint16 poly_0012BCC0[] = {
	4, 6, 7, 4, 5,
	4, 3, 9, 1, 8,
	4, 19, 15, 18, 14,
	4, 17, 21, 16, 20
};

Sint16 poly_0012BCE8[] = {
	4, 11, 6, 10, 4,
	4, 9, 13, 8, 12
};

Sint16 poly_0012BCFC[] = {
	4, 17, 13, 21, 25,
	4, 19, 27, 15, 11,
	4, 18, 14, 26, 10,
	4, 12, 16, 24, 20
};

Sint16 poly_0012BD24[] = {
	4, 25, 27, 24, 26
};

NJS_TEX uv_0012BD30[] = {
	{ 0, 255 },
	{ 0, -1275 },
	{ 253, 255 },
	{ 253, -1275 }
};

NJS_TEX uv_0012BD40[] = {
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 0, 3 },
	{ 3060, 3 },
	{ 0, 255 },
	{ 3060, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 3060, 3 },
	{ 3060, 255 }
};

NJS_TEX uv_0012BDB8[] = {
	{ 0, 255 },
	{ 0, 1 },
	{ 76, 255 },
	{ 76, 1 },
	{ 1453, 254 },
	{ 1453, 1 },
	{ 1529, 254 },
	{ 1529, 1 },
	{ 1530, 255 },
	{ 1530, 1 },
	{ 1453, 255 },
	{ 1453, 1 },
	{ 76, 255 },
	{ 76, 1 },
	{ 0, 255 },
	{ 0, 1 }
};

NJS_TEX uv_0012BDF8[] = {
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 }
};

NJS_TEX uv_0012BE38[] = {
	{ 0, 1 },
	{ 0, 255 },
	{ 253, 1 },
	{ 253, 255 },
	{ 253, 255 },
	{ 253, 1 },
	{ 0, 255 },
	{ 0, 1 }
};

NJS_TEX uv_0012BE58[] = {
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 255 },
	{ 0, 3 },
	{ 251, 255 },
	{ 251, 3 }
};

NJS_TEX uv_0012BE98[] = {
	{ 0, -1275 },
	{ 0, 255 },
	{ 253, -1275 },
	{ 253, 255 }
};

NJS_MESHSET_SADX meshlist_0012BEA8[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_0012BC48, NULL, NULL, NULL, uv_0012BD30, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 7, poly_0012BC52, NULL, NULL, NULL, uv_0012BD40, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_0012BC9C, NULL, NULL, NULL, uv_0012BDB8, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 4, poly_0012BCC0, NULL, NULL, NULL, uv_0012BDF8, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_0012BCE8, NULL, NULL, NULL, uv_0012BE38, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 4, poly_0012BCFC, NULL, NULL, NULL, uv_0012BE58, NULL },
	{ NJD_MESHSET_TRIMESH | 6, 1, poly_0012BD24, NULL, NULL, NULL, uv_0012BE98, NULL }
};

NJS_VECTOR vertex_0012BF50[] = {
	{ 45.92612f, 0.000001f, 19.99997f },
	{ 45.92612f, 5.000001f, 19.99997f },
	{ 45.92612f, 0.000002f, -9.850192f },
	{ 45.92612f, 5.000002f, -9.850192f },
	{ -49.07388f, 5.000002f, 19.99997f },
	{ -44.07388f, 5.000002f, 19.99997f },
	{ -49.07388f, 5.000003f, -19.20689f },
	{ -44.07388f, 5.000003f, -18.71444f },
	{ 50.92612f, 5.000001f, 19.99997f },
	{ 50.92612f, 5.000002f, -9.357735f },
	{ -49.07388f, 20, 19.99997f },
	{ -49.07388f, 20, -19.20689f },
	{ 50.92612f, 20, 19.99997f },
	{ 50.92612f, 20, -9.357735f },
	{ -49.07388f, 25, 19.99997f },
	{ -49.07388f, 25, -19.20689f },
	{ 50.92612f, 25, 19.99997f },
	{ 50.92612f, 25, -9.357735f },
	{ -44.07388f, 25, 19.99997f },
	{ -44.07388f, 25, -18.71444f },
	{ 45.92612f, 25, 19.99997f },
	{ 45.92612f, 25, -9.850192f },
	{ -44.07388f, 0.000002f, 19.99997f },
	{ -44.07388f, 0.000003f, -18.71444f },
	{ 45.92612f, 20, 19.99997f },
	{ 45.92612f, 20, -9.850192f },
	{ -44.07388f, 20, 19.99997f },
	{ -44.07388f, 20, -18.71444f }
};

NJS_VECTOR normal_0012C0A0[] = {
	{ 0.57735f, -0.57735f, 0.57735f },
	{ 0.301511f, -0.301511f, 0.904534f },
	{ 0.602167f, -0.582689f, -0.545773f },
	{ 0.382144f, -0.276851f, -0.8816569f },
	{ -0.57735f, -0.57735f, 0.57735f },
	{ -0.301511f, -0.301511f, 0.904534f },
	{ -0.550679f, -0.572363f, -0.6075799f },
	{ -0.217438f, -0.327259f, -0.9195769f },
	{ 0.57735f, -0.57735f, 0.57735f },
	{ 0.602167f, -0.582689f, -0.545773f },
	{ -0.7071069f, 0, 0.7071069f },
	{ -0.671559f, 0, -0.7409509f },
	{ 0.7071069f, 0, 0.7071069f },
	{ 0.7409509f, 0, -0.671559f },
	{ -0.57735f, 0.57735f, 0.57735f },
	{ -0.550679f, 0.572363f, -0.6075799f },
	{ 0.57735f, 0.57735f, 0.57735f },
	{ 0.602167f, 0.582689f, -0.545773f },
	{ 0.57735f, 0.57735f, 0.57735f },
	{ 0.602167f, 0.582689f, -0.545773f },
	{ -0.57735f, 0.57735f, 0.57735f },
	{ -0.550679f, 0.572363f, -0.6075799f },
	{ -0.57735f, -0.57735f, 0.57735f },
	{ -0.550679f, -0.572363f, -0.6075799f },
	{ -0.301511f, 0.301511f, 0.904534f },
	{ -0.217438f, 0.327259f, -0.9195769f },
	{ 0.301511f, 0.301511f, 0.904534f },
	{ 0.382143f, 0.276851f, -0.8816569f }
};

NJS_MODEL_SADX attach_0012C1F0 = { vertex_0012BF50, normal_0012C0A0, LengthOfArray(vertex_0012BF50), meshlist_0012BEA8, matlist_0012BBBC, LengthOfArray(meshlist_0012BEA8), LengthOfArray(matlist_0012BBBC),{ 0.9261169f, 12.5f, 0.396538f }, 53.70562f, NULL };

NJS_OBJECT object_0012C218 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_0012C1F0, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Ashiba03

NJS_MATERIAL matlist_0012C24C[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_29, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_24, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_vq128_los042, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_vq128_los042, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_29, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_7, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_0012C2D8[] = {
	3, 23, 3, 6,
	0x8000u | 5, 6, 2, 3, 1, 0,
	4, 11, 15, 10, 14,
	4, 17, 13, 16, 12,
	4, 19, 27, 18, 26,
	4, 23, 6, 22, 5,
	4, 25, 21, 24, 20,
	4, 22, 5, 0, 1
};

Sint16 poly_0012C328[] = {
	4, 3, 23, 0, 22
};

Sint16 poly_0012C332[] = {
	4, 6, 7, 5, 4,
	4, 9, 2, 8, 1,
	4, 15, 19, 14, 18,
	4, 21, 17, 20, 16
};

Sint16 poly_0012C35A[] = {
	0x8000u | 8, 7, 11, 6, 27, 2, 25, 9, 13,
	8, 4, 10, 5, 26, 1, 24, 8, 12
};

Sint16 poly_0012C37E[] = {
	4, 7, 11, 4, 10,
	4, 13, 9, 12, 8
};

Sint16 poly_0012C392[] = {
	4, 17, 21, 13, 25,
	4, 15, 11, 19, 27,
	4, 20, 16, 24, 12,
	4, 10, 14, 26, 18
};

Sint16 poly_0012C3BA[] = {
	4, 27, 25, 26, 24
};

NJS_TEX uv_0012C3C4[] = {
	{ 3060, 255 },
	{ 0, 255 },
	{ 3060, 3 },
	{ 3060, 3 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 3060, 255 },
	{ 3060, 3 },
	{ 0, 255 },
	{ 0, 3 }
};

NJS_TEX uv_0012C444[] = {
	{ 253, -1275 },
	{ 253, 255 },
	{ 0, -1275 },
	{ 0, 255 }
};

NJS_TEX uv_0012C454[] = {
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 1275, 255 },
	{ 1275, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 1275, 3 },
	{ 1275, 255 }
};

NJS_TEX uv_0012C494[] = {
	{ 0, 255 },
	{ 0, 1 },
	{ 76, 255 },
	{ 76, 1 },
	{ 1453, 255 },
	{ 1453, 1 },
	{ 1530, 255 },
	{ 1530, 1 },
	{ 1529, 254 },
	{ 1529, 1 },
	{ 1453, 254 },
	{ 1453, 1 },
	{ 76, 254 },
	{ 76, 1 },
	{ 0, 254 },
	{ 0, 1 }
};

NJS_TEX uv_0012C4D4[] = {
	{ 253, 255 },
	{ 253, 1 },
	{ 0, 255 },
	{ 0, 1 },
	{ 0, 1 },
	{ 0, 255 },
	{ 253, 1 },
	{ 253, 255 }
};

NJS_TEX uv_0012C4F4[] = {
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 255 },
	{ 0, 255 },
	{ 251, 255 },
	{ 251, 3 },
	{ 0, 255 },
	{ 0, 3 }
};

NJS_TEX uv_0012C534[] = {
	{ 253, 255 },
	{ 253, -1275 },
	{ 0, 255 },
	{ 0, -1275 }
};

NJS_MESHSET_SADX meshlist_0012C544[] = {
	{ NJD_MESHSET_TRIMESH | 0, 8, poly_0012C2D8, NULL, NULL, NULL, uv_0012C3C4, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 1, poly_0012C328, NULL, NULL, NULL, uv_0012C444, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 4, poly_0012C332, NULL, NULL, NULL, uv_0012C454, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 2, poly_0012C35A, NULL, NULL, NULL, uv_0012C494, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_0012C37E, NULL, NULL, NULL, uv_0012C4D4, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 4, poly_0012C392, NULL, NULL, NULL, uv_0012C4F4, NULL },
	{ NJD_MESHSET_TRIMESH | 6, 1, poly_0012C3BA, NULL, NULL, NULL, uv_0012C534, NULL }
};

NJS_VECTOR vertex_0012C5EC[] = {
	{ 45.92612f, 0.000001f, -20.00003f },
	{ 45.92612f, 5.000001f, -20.00003f },
	{ 45.92612f, 5, 9.850148f },
	{ 45.92612f, 0, 9.850148f },
	{ -49.07388f, 5.000002f, -20.00003f },
	{ -44.07388f, 5.000002f, -20.00003f },
	{ -44.07388f, 5, 18.71437f },
	{ -49.07388f, 5, 19.20682f },
	{ 50.92612f, 5.000001f, -20.00003f },
	{ 50.92612f, 5, 9.357693f },
	{ -49.07388f, 20, -20.00003f },
	{ -49.07388f, 20, 19.20682f },
	{ 50.92612f, 20, -20.00003f },
	{ 50.92612f, 20, 9.357693f },
	{ -49.07388f, 25, -20.00003f },
	{ -49.07388f, 25, 19.20682f },
	{ 50.92612f, 25, -20.00003f },
	{ 50.92612f, 25, 9.357693f },
	{ -44.07388f, 25, -20.00003f },
	{ -44.07388f, 25, 18.71437f },
	{ 45.92612f, 25, -20.00003f },
	{ 45.92612f, 25, 9.850148f },
	{ -44.07388f, 0.000002f, -20.00003f },
	{ -44.07388f, 0, 18.71437f },
	{ 45.92612f, 20, -20.00003f },
	{ 45.92612f, 20, 9.850148f },
	{ -44.07388f, 20, -20.00003f },
	{ -44.07388f, 20, 18.71437f }
};

NJS_VECTOR normal_0012C73C[] = {
	{ 0.57735f, -0.57735f, -0.57735f },
	{ 0.301511f, -0.301511f, -0.904534f },
	{ 0.382143f, -0.276851f, 0.8816569f },
	{ 0.602167f, -0.582689f, 0.545773f },
	{ -0.57735f, -0.57735f, -0.57735f },
	{ -0.301511f, -0.301511f, -0.904534f },
	{ -0.217439f, -0.327259f, 0.9195769f },
	{ -0.550679f, -0.572363f, 0.6075799f },
	{ 0.57735f, -0.57735f, -0.57735f },
	{ 0.602167f, -0.582689f, 0.545773f },
	{ -0.7071069f, 0, -0.7071069f },
	{ -0.671559f, 0, 0.7409509f },
	{ 0.7071069f, 0, -0.7071069f },
	{ 0.7409509f, 0, 0.671559f },
	{ -0.57735f, 0.57735f, -0.57735f },
	{ -0.550679f, 0.572363f, 0.6075799f },
	{ 0.57735f, 0.57735f, -0.57735f },
	{ 0.602167f, 0.582689f, 0.545773f },
	{ 0.57735f, 0.57735f, -0.57735f },
	{ 0.602167f, 0.582689f, 0.545773f },
	{ -0.57735f, 0.57735f, -0.57735f },
	{ -0.550679f, 0.572363f, 0.6075799f },
	{ -0.57735f, -0.57735f, -0.57735f },
	{ -0.550679f, -0.572363f, 0.6075799f },
	{ -0.301511f, 0.301511f, -0.904534f },
	{ -0.217438f, 0.327259f, 0.9195769f },
	{ 0.301511f, 0.301511f, -0.904534f },
	{ 0.382143f, 0.276851f, 0.881658f }
};

NJS_MODEL_SADX attach_0012C88C = { vertex_0012C5EC, normal_0012C73C, LengthOfArray(vertex_0012C5EC), meshlist_0012C544, matlist_0012C24C, LengthOfArray(meshlist_0012C544), LengthOfArray(matlist_0012C24C),{ 0.9261169f, 12.5f, -0.396606f }, 53.70562f, NULL };

NJS_OBJECT object_0012C8B4 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_0012C88C, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Snake head

NJS_MATERIAL matlist_00146668[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw030, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw031, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw029, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw017, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw018, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw018, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw027, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw018, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw028, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw024, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw024, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw022, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw022, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw017, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw026, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw019, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw025, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw023, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw023, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00146870[] = {
	3, 3, 1, 0,
	3, 1, 2, 0,
	3, 2, 3, 0,
	3, 4, 5, 7,
	3, 4, 6, 5,
	3, 4, 7, 6
};

Sint16 poly_001468A0[] = {
	4, 24, 8, 10, 12,
	0x8000u | 5, 18, 20, 8, 22, 24,
	5, 18, 16, 8, 14, 12,
	4, 41, 27, 25, 29,
	5, 35, 37, 25, 39, 41,
	0x8000u | 5, 35, 33, 25, 31, 29
};

Sint16 poly_001468E4[] = {
	4, 9, 23, 10, 24,
	4, 11, 9, 12, 10,
	4, 23, 21, 24, 22,
	4, 13, 11, 14, 12,
	4, 21, 19, 22, 20,
	4, 15, 13, 16, 14,
	4, 19, 17, 20, 18,
	4, 17, 15, 18, 16,
	4, 27, 41, 26, 40,
	4, 29, 27, 28, 26,
	4, 41, 39, 40, 38,
	4, 31, 29, 30, 28,
	4, 39, 37, 38, 36,
	4, 33, 31, 32, 30,
	4, 37, 35, 36, 34,
	4, 35, 33, 34, 32
};

Sint16 poly_00146984[] = {
	0x8000u | 5, 43, 44, 45, 47, 46,
	3, 43, 42, 45,
	0x8000u | 5, 48, 51, 50, 52, 53,
	3, 48, 49, 50,
	4, 97, 113, 77, 114,
	4, 118, 134, 94, 135,
	4, 88, 123, 84, 112,
	4, 90, 121, 88, 122,
	4, 112, 132, 84, 133,
	4, 77, 114, 76, 115,
	4, 76, 115, 80, 116,
	4, 80, 116, 81, 117,
	4, 81, 117, 94, 118,
	4, 86, 119, 90, 120,
	4, 97, 133, 113, 132,
	4, 86, 135, 119, 134
};

Sint16 poly_00146A24[] = {
	3, 45, 42, 46,
	3, 52, 48, 51,
	3, 121, 90, 120,
	3, 123, 88, 122
};

Sint16 poly_00146A44[] = {
	4, 81, 94, 77, 97,
	4, 77, 76, 81, 80,
	4, 84, 133, 86, 135,
	4, 90, 88, 86, 84,
	4, 72, 100, 74, 101,
	4, 65, 64, 69, 68,
	4, 100, 127, 101, 125,
	4, 69, 125, 65, 127,
	4, 94, 135, 97, 133
};

Sint16 poly_00146A9E[] = {
	4, 95, 104, 83, 105,
	4, 79, 108, 96, 109
};

Sint16 poly_00146AB2[] = {
	4, 79, 96, 83, 95,
	4, 83, 82, 79, 78,
	4, 87, 128, 85, 129,
	4, 85, 93, 87, 92,
	4, 57, 56, 55, 54,
	4, 96, 129, 95, 128
};

Sint16 poly_00146AEE[] = {
	4, 78, 107, 79, 108,
	4, 83, 105, 82, 106
};

Sint16 poly_00146B02[] = {
	4, 89, 122, 91, 121
};

Sint16 poly_00146B0C[] = {
	4, 82, 106, 78, 107
};

Sint16 poly_00146B16[] = {
	4, 109, 131, 96, 129,
	4, 95, 128, 104, 130
};

Sint16 poly_00146B2A[] = {
	4, 91, 92, 89, 93
};

Sint16 poly_00146B34[] = {
	3, 89, 93, 111,
	4, 92, 102, 87, 103,
	4, 85, 110, 93, 111,
	4, 103, 130, 87, 128,
	3, 102, 92, 91,
	4, 85, 129, 110, 131
};

Sint16 poly_00146B6C[] = {
	4, 73, 99, 72, 100,
	4, 74, 101, 75, 98,
	4, 70, 71, 68, 69,
	4, 75, 73, 74, 72,
	4, 67, 66, 65, 64
};

Sint16 poly_00146B9E[] = {
	4, 66, 70, 64, 68,
	4, 101, 125, 98, 124,
	4, 99, 126, 100, 127,
	4, 71, 124, 69, 125,
	4, 65, 127, 67, 126
};

Sint16 poly_00146BD0[] = {
	0x8000u | 6, 61, 60, 63, 62, 58, 59
};

Sint16 poly_00146BDE[] = {
	4, 54, 59, 55, 58,
	4, 57, 61, 56, 60
};

Sint16 poly_00146BF2[] = {
	4, 111, 123, 89, 122,
	4, 91, 121, 102, 120
};

Sint16 poly_00146C06[] = {
	4, 102, 120, 103, 119,
	4, 119, 134, 103, 130,
	4, 110, 112, 111, 123,
	4, 110, 131, 112, 132
};

Sint16 poly_00146C2E[] = {
	4, 104, 118, 105, 117,
	4, 108, 114, 109, 113
};

Sint16 poly_00146C42[] = {
	4, 105, 117, 106, 116,
	4, 107, 115, 108, 114
};

Sint16 poly_00146C56[] = {
	4, 106, 116, 107, 115
};

Sint16 poly_00146C60[] = {
	4, 113, 132, 109, 131,
	4, 104, 130, 118, 134
};

Sint16 poly_00146C74[] = {
	4, 56, 60, 54, 59
};

Sint16 poly_00146C7E[] = {
	3, 60, 62, 59
};

NJS_TEX uv_00146C88[] = {
	{ 245, -253 },
	{ 0, -253 },
	{ 116, 254 },
	{ 245, -253 },
	{ 0, -253 },
	{ 116, 254 },
	{ 245, -253 },
	{ 0, -253 },
	{ 116, 254 },
	{ 116, 254 },
	{ 245, -253 },
	{ 0, -253 },
	{ 116, 254 },
	{ 245, -253 },
	{ 0, -253 },
	{ 116, 254 },
	{ 245, -253 },
	{ 0, -253 }
};

NJS_TEX uv_00146CD0[] = {
	{ 441, -175 },
	{ 251, -14 },
	{ 263, -254 },
	{ 80, -185 },
	{ 246, 255 },
	{ 429, 185 },
	{ 251, -14 },
	{ 510, 6 },
	{ 441, -175 },
	{ 246, 255 },
	{ 68, 175 },
	{ 251, -14 },
	{ 0, -6 },
	{ 80, -185 },
	{ 441, -175 },
	{ 263, -255 },
	{ 251, -14 },
	{ 80, -185 },
	{ 246, 255 },
	{ 429, 185 },
	{ 251, -14 },
	{ 510, 6 },
	{ 441, -175 },
	{ 246, 255 },
	{ 68, 175 },
	{ 251, -14 },
	{ 0, -6 },
	{ 80, -185 }
};

NJS_TEX uv_00146D40[] = {
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 247, 7 },
	{ 247, 255 },
	{ 0, 7 },
	{ 0, 255 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 },
	{ 0, 255 },
	{ 0, 7 },
	{ 247, 255 },
	{ 247, 7 }
};

NJS_TEX uv_00146E40[] = {
	{ 763, 170 },
	{ 765, 7 },
	{ 0, 7 },
	{ 763, 170 },
	{ -1, 170 },
	{ 763, 170 },
	{ -1, 170 },
	{ 0, 7 },
	{ -1, 170 },
	{ 0, 7 },
	{ 765, 7 },
	{ -1, 170 },
	{ 763, 170 },
	{ -1, 170 },
	{ 763, 170 },
	{ 765, 7 },
	{ 1020, 7 },
	{ 1020, 171 },
	{ 0, 7 },
	{ 0, 171 },
	{ 0, 170 },
	{ 510, 170 },
	{ 0, 7 },
	{ 510, 7 },
	{ 510, 7 },
	{ 510, 170 },
	{ 0, 7 },
	{ 0, 170 },
	{ 763, 9 },
	{ 688, 171 },
	{ 1, 9 },
	{ 64, 171 },
	{ 510, 170 },
	{ 0, 170 },
	{ 510, 7 },
	{ 0, 7 },
	{ 510, 7 },
	{ 510, 170 },
	{ 0, 7 },
	{ 0, 170 },
	{ 0, 7 },
	{ 0, 171 },
	{ 1020, 7 },
	{ 1020, 171 },
	{ 0, 7 },
	{ 0, 170 },
	{ 510, 7 },
	{ 510, 170 },
	{ 0, 7 },
	{ 0, 171 },
	{ 1020, 7 },
	{ 1020, 171 },
	{ 0, 7 },
	{ 0, 170 },
	{ 510, 7 },
	{ 510, 170 },
	{ 0, 7 },
	{ 510, 7 },
	{ 0, 170 },
	{ 510, 170 },
	{ 510, 7 },
	{ 0, 7 },
	{ 510, 170 },
	{ 0, 170 }
};

NJS_TEX uv_00146F40[] = {
	{ 61, 9 },
	{ 123, 170 },
	{ 0, 170 },
	{ 0, 170 },
	{ 123, 170 },
	{ 61, 9 },
	{ 123, 170 },
	{ 61, 9 },
	{ 0, 170 },
	{ 0, 170 },
	{ 61, 9 },
	{ 123, 170 }
};

NJS_TEX uv_00146F70[] = {
	{ 506, -253 },
	{ 510, 255 },
	{ 0, -252 },
	{ 0, 255 },
	{ 0, 4 },
	{ 0, -251 },
	{ 510, 3 },
	{ 510, -252 },
	{ -1, 2 },
	{ -1, -251 },
	{ 508, 2 },
	{ 508, -251 },
	{ 510, 255 },
	{ 0, 255 },
	{ 510, 3 },
	{ 0, 3 },
	{ 438, 9 },
	{ 459, 255 },
	{ 86, 9 },
	{ 69, 255 },
	{ 510, -250 },
	{ 473, 0 },
	{ 0, -251 },
	{ 31, 0 },
	{ 457, -252 },
	{ 494, 257 },
	{ 70, -252 },
	{ 17, 255 },
	{ 0, 255 },
	{ 18, -253 },
	{ 510, 255 },
	{ 491, -255 },
	{ 510, 3 },
	{ 510, 255 },
	{ 0, 3 },
	{ 0, 255 }
};

NJS_TEX uv_00147000[] = {
	{ 0, 3 },
	{ 0, 255 },
	{ 510, 3 },
	{ 510, 255 },
	{ 510, 3 },
	{ 510, 255 },
	{ 0, 3 },
	{ 0, 255 }
};

NJS_TEX uv_00147020[] = {
	{ 253, 1 },
	{ 244, 255 },
	{ 0, 1 },
	{ 5, 255 },
	{ 0, 174 },
	{ 13, 11 },
	{ 252, 174 },
	{ 238, 10 },
	{ 204, 198 },
	{ 230, 68 },
	{ 40, 198 },
	{ 19, 69 },
	{ 212, 152 },
	{ 183, 255 },
	{ 36, 152 },
	{ 55, 255 },
	{ 0, 255 },
	{ 0, 1 },
	{ 253, 255 },
	{ 253, 1 },
	{ 243, 2 },
	{ 223, 110 },
	{ 9, 3 },
	{ 24, 110 }
};

NJS_TEX uv_00147080[] = {
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 }
};

NJS_TEX uv_001470A0[] = {
	{ 14, 8 },
	{ 0, 255 },
	{ 492, 7 },
	{ 510, 255 }
};

NJS_TEX uv_001470B0[] = {
	{ 510, 3 },
	{ 510, 255 },
	{ 0, 3 },
	{ 0, 255 }
};

NJS_TEX uv_001470C0[] = {
	{ 251, 255 },
	{ 0, 255 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 255 },
	{ 0, 255 }
};

NJS_TEX uv_001470E0[] = {
	{ 20, 255 },
	{ 0, 3 },
	{ 489, 254 },
	{ 510, 3 }
};

NJS_TEX uv_001470F0[] = {
	{ 251, 255 },
	{ 0, 4 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 251, 255 },
	{ 0, 255 },
	{ 251, 3 },
	{ 0, 3 },
	{ 0, 255 },
	{ 0, 4 },
	{ 251, 255 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 255 },
	{ 0, 255 }
};

NJS_TEX uv_00147148[] = {
	{ 247, -255 },
	{ 247, 255 },
	{ 0, -255 },
	{ 0, 255 },
	{ 0, 255 },
	{ 0, -255 },
	{ 247, 255 },
	{ 247, -255 },
	{ 247, 255 },
	{ 247, -255 },
	{ 0, 255 },
	{ 0, -255 },
	{ 247, -255 },
	{ 247, 255 },
	{ 0, -255 },
	{ 0, 255 },
	{ 247, -255 },
	{ 247, 255 },
	{ 0, -255 },
	{ 0, 255 }
};

NJS_TEX uv_00147198[] = {
	{ 247, 255 },
	{ 247, -765 },
	{ 0, 255 },
	{ 0, -764 },
	{ 0, -764 },
	{ 0, 255 },
	{ 247, -765 },
	{ 247, 255 },
	{ 247, -765 },
	{ 247, 255 },
	{ 0, -764 },
	{ 0, 255 },
	{ 247, 255 },
	{ 247, -765 },
	{ 0, 255 },
	{ 0, -764 },
	{ 0, 255 },
	{ 0, -764 },
	{ 247, 255 },
	{ 247, -765 }
};

NJS_TEX uv_001471E8[] = {
	{ 0, -254 },
	{ 0, 255 },
	{ 251, -255 },
	{ 251, 255 },
	{ 0, -254 },
	{ 0, 255 }
};

NJS_TEX uv_00147200[] = {
	{ 509, 255 },
	{ 510, -255 },
	{ 0, 255 },
	{ 0, -255 },
	{ 0, 255 },
	{ 0, -255 },
	{ 509, 255 },
	{ 510, -255 }
};

NJS_TEX uv_00147220[] = {
	{ 0, -255 },
	{ 0, 255 },
	{ 247, -255 },
	{ 247, 255 },
	{ 247, -255 },
	{ 247, 255 },
	{ 0, -255 },
	{ 0, 255 }
};

NJS_TEX uv_00147240[] = {
	{ 0, 16 },
	{ 0, 238 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 251 },
	{ 251, 255 },
	{ 0, 12 },
	{ 251, 3 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 16 },
	{ 0, 238 },
	{ 0, 12 },
	{ 251, 3 },
	{ 0, 251 },
	{ 251, 255 }
};

NJS_TEX uv_00147280[] = {
	{ 0, 3 },
	{ 0, 255 },
	{ 510, 3 },
	{ 510, 255 },
	{ 510, 3 },
	{ 510, 255 },
	{ 0, 3 },
	{ 0, 255 }
};

NJS_TEX uv_001472A0[] = {
	{ 0, 3 },
	{ 0, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 251, 3 },
	{ 251, 255 },
	{ 0, 3 },
	{ 0, 255 }
};

NJS_TEX uv_001472C0[] = {
	{ 510, 3 },
	{ 510, 255 },
	{ 0, 3 },
	{ 0, 255 }
};

NJS_TEX uv_001472D0[] = {
	{ 251, 255 },
	{ 0, 255 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 3 },
	{ 251, 255 },
	{ 0, 255 }
};

NJS_TEX uv_001472F0[] = {
	{ 0, -255 },
	{ 0, 255 },
	{ 510, -255 },
	{ 509, 255 }
};

NJS_TEX uv_00147300[] = {
	{ 0, 4 },
	{ 255, 255 },
	{ 507, 3 }
};

NJS_MESHSET_SADX meshlist_0014730C[] = {
	{ NJD_MESHSET_TRIMESH | 0, 6, poly_00146870, NULL, NULL, NULL, uv_00146C88, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 6, poly_001468A0, NULL, NULL, NULL, uv_00146CD0, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 16, poly_001468E4, NULL, NULL, NULL, uv_00146D40, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 16, poly_00146984, NULL, NULL, NULL, uv_00146E40, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 4, poly_00146A24, NULL, NULL, NULL, uv_00146F40, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 9, poly_00146A44, NULL, NULL, NULL, uv_00146F70, NULL },
	{ NJD_MESHSET_TRIMESH | 6, 2, poly_00146A9E, NULL, NULL, NULL, uv_00147000, NULL },
	{ NJD_MESHSET_TRIMESH | 7, 6, poly_00146AB2, NULL, NULL, NULL, uv_00147020, NULL },
	{ NJD_MESHSET_TRIMESH | 8, 2, poly_00146AEE, NULL, NULL, NULL, uv_00147080, NULL },
	{ NJD_MESHSET_TRIMESH | 9, 1, poly_00146B02, NULL, NULL, NULL, uv_001470A0, NULL },
	{ NJD_MESHSET_TRIMESH | 10, 1, poly_00146B0C, NULL, NULL, NULL, uv_001470B0, NULL },
	{ NJD_MESHSET_TRIMESH | 11, 2, poly_00146B16, NULL, NULL, NULL, uv_001470C0, NULL },
	{ NJD_MESHSET_TRIMESH | 12, 1, poly_00146B2A, NULL, NULL, NULL, uv_001470E0, NULL },
	{ NJD_MESHSET_TRIMESH | 13, 6, poly_00146B34, NULL, NULL, NULL, uv_001470F0, NULL },
	{ NJD_MESHSET_TRIMESH | 14, 5, poly_00146B6C, NULL, NULL, NULL, uv_00147148, NULL },
	{ NJD_MESHSET_TRIMESH | 15, 5, poly_00146B9E, NULL, NULL, NULL, uv_00147198, NULL },
	{ NJD_MESHSET_TRIMESH | 16, 1, poly_00146BD0, NULL, NULL, NULL, uv_001471E8, NULL },
	{ NJD_MESHSET_TRIMESH | 17, 2, poly_00146BDE, NULL, NULL, NULL, uv_00147200, NULL },
	{ NJD_MESHSET_TRIMESH | 18, 2, poly_00146BF2, NULL, NULL, NULL, uv_00147220, NULL },
	{ NJD_MESHSET_TRIMESH | 19, 4, poly_00146C06, NULL, NULL, NULL, uv_00147240, NULL },
	{ NJD_MESHSET_TRIMESH | 20, 2, poly_00146C2E, NULL, NULL, NULL, uv_00147280, NULL },
	{ NJD_MESHSET_TRIMESH | 21, 2, poly_00146C42, NULL, NULL, NULL, uv_001472A0, NULL },
	{ NJD_MESHSET_TRIMESH | 22, 1, poly_00146C56, NULL, NULL, NULL, uv_001472C0, NULL },
	{ NJD_MESHSET_TRIMESH | 23, 2, poly_00146C60, NULL, NULL, NULL, uv_001472D0, NULL },
	{ NJD_MESHSET_TRIMESH | 24, 1, poly_00146C74, NULL, NULL, NULL, uv_001472F0, NULL },
	{ NJD_MESHSET_TRIMESH | 25, 1, poly_00146C7E, NULL, NULL, NULL, uv_00147300, NULL }
};

NJS_VECTOR vertex_0014757C[] = {
	{ 12.9f, -14.64f, 56.97499f },
	{ 13.4f, -8.080001f, 59.163f },
	{ 9.95f, -7.54f, 60.854f },
	{ 13.05f, -8.620002f, 57.672f },
	{ -12.9f, -14.64f, 56.97499f },
	{ -13.4f, -8.080001f, 59.163f },
	{ -9.95f, -7.54f, 60.854f },
	{ -13.05f, -8.620002f, 57.672f },
	{ 19.801f, 5.648997f, 48.93399f },
	{ 14.296f, 9.684999f, 47.59999f },
	{ 17.045f, 9.143997f, 48.543f },
	{ 16.409f, 8.678996f, 43.50499f },
	{ 18.508f, 8.432996f, 45.64799f },
	{ 18.81f, 4.990997f, 41.80899f },
	{ 20.171f, 5.824997f, 44.44799f },
	{ 20.092f, 0.780998f, 43.50499f },
	{ 21.059f, 2.847997f, 45.64799f },
	{ 19.504f, -1.485f, 47.59999f },
	{ 20.652f, 1.245998f, 48.543f },
	{ 17.391f, -0.479002f, 51.695f },
	{ 19.188f, 1.956997f, 51.439f },
	{ 14.99f, 3.208997f, 53.391f },
	{ 17.526f, 4.564998f, 52.638f },
	{ 13.708f, 7.418998f, 51.695f },
	{ 16.638f, 7.541998f, 51.439f },
	{ -19.605f, 5.648997f, 48.93399f },
	{ -14.096f, 9.684999f, 47.59999f },
	{ -16.849f, 9.143997f, 48.543f },
	{ -16.209f, 8.678996f, 43.50499f },
	{ -18.313f, 8.432996f, 45.64799f },
	{ -18.61f, 4.990997f, 41.80899f },
	{ -19.975f, 5.824997f, 44.44799f },
	{ -19.892f, 0.780998f, 43.50499f },
	{ -20.863f, 2.847997f, 45.64799f },
	{ -19.304f, -1.485f, 47.59999f },
	{ -20.456f, 1.245998f, 48.543f },
	{ -17.191f, -0.479002f, 51.695f },
	{ -18.992f, 1.956997f, 51.439f },
	{ -14.79f, 3.208997f, 53.391f },
	{ -17.33f, 4.564998f, 52.638f },
	{ -13.508f, 7.418998f, 51.695f },
	{ -16.442f, 7.541998f, 51.439f },
	{ -12, 15, -17.50001f },
	{ -12, 12.9f, 5.099995f },
	{ -13, 13.90001f, 4.099995f },
	{ -13, 19, -17.50001f },
	{ -14, 15, -17.50001f },
	{ -14, 12.9f, 5.099995f },
	{ 12, 15, -17.50001f },
	{ 12, 12.9f, 5.099995f },
	{ 13, 13.90001f, 4.099995f },
	{ 13, 19, -17.50001f },
	{ 14, 15, -17.50001f },
	{ 14, 12.9f, 5.099995f },
	{ -14.3f, 15.025f, -17.50001f },
	{ -14.3f, 13.225f, 6.549995f },
	{ 14.2f, 15.025f, -17.50001f },
	{ 14.2f, 13.225f, 6.549995f },
	{ -19.4f, -5.374999f, 10.24999f },
	{ -19.5f, -5.599999f, -17.50001f },
	{ 19.5f, -5.6f, -17.50001f },
	{ 19.5f, -5.374999f, 10.24999f },
	{ 0, -18.1f, -17.50001f },
	{ 0, -17.25001f, 12.87499f },
	{ -15.625f, -15.725f, 5.474995f },
	{ -20.625f, -17.50001f, 14.32499f },
	{ -17.6755f, -11.85f, -0.575004f },
	{ -23.7705f, -13.15f, 14.29999f },
	{ 15.625f, -15.725f, 5.474995f },
	{ 20.625f, -17.50001f, 14.32499f },
	{ 17.6755f, -11.85f, -0.575004f },
	{ 23.7705f, -13.15f, 14.32999f },
	{ -5, -8.075002f, 66.19998f },
	{ -5.59f, -5.049998f, 67.94998f },
	{ 5, -8.075002f, 66.19998f },
	{ 5.59f, -5.049998f, 67.94998f },
	{ -18.724f, -11.85f, -0.575007f },
	{ -25.16f, -13.15f, 14.32499f },
	{ -15.113f, 13.95001f, 4.024994f },
	{ -18.309f, 14.72501f, 14.32499f },
	{ 18.724f, -11.85f, -0.575007f },
	{ 25.16f, -13.15f, 14.32499f },
	{ 15.113f, 13.95001f, 4.024994f },
	{ 18.309f, 14.72501f, 14.32499f },
	{ -13.774f, -8.450002f, 58.34999f },
	{ -9.304f, 9.375f, 58.55f },
	{ 13.774f, -8.450002f, 58.34999f },
	{ 9.304f, 9.375f, 58.55f },
	{ -8.377999f, -5.049998f, 67.92499f },
	{ -5.088f, 0.649999f, 71.12498f },
	{ 8.419999f, -5.049998f, 67.92499f },
	{ 5.088f, 0.649999f, 71.12498f },
	{ 6.658f, 5.399998f, 68.32498f },
	{ -6.658f, 5.399998f, 68.32498f },
	{ 22.477f, -12.75f, 35.83799f },
	{ 16.184f, 15.60001f, 35.83799f },
	{ -16.184f, 15.60001f, 35.83799f },
	{ -22.477f, -12.75f, 35.83799f },
	{ 12.175f, -8.456f, 58.31f },
	{ -12.175f, -8.456f, 58.308f },
	{ -10.649f, -12.088f, 56.563f },
	{ 10.649f, -12.088f, 56.563f },
	{ 8.853999f, 0.674998f, 68.42499f },
	{ 14.433f, 1.862997f, 58.65f },
	{ 23.669f, 2.524997f, 35.83799f },
	{ 26.569f, 2.587997f, 14.32499f },
	{ 19.756f, 2.449997f, -1.875006f },
	{ -19.756f, 2.449997f, -1.875006f },
	{ -26.569f, 2.587997f, 14.32499f },
	{ -23.669f, 2.524997f, 35.83799f },
	{ -14.433f, 1.862997f, 58.65f },
	{ -8.778999f, 0.674998f, 68.42499f },
	{ -14.769f, -5.697f, 58.7f },
	{ -24.132f, -9.981002f, 35.83799f },
	{ -27.032f, -9.591002f, 14.32499f },
	{ -20.113f, -9.525002f, -1.225005f },
	{ 20.113f, -9.525002f, -1.225005f },
	{ 27.032f, -9.591002f, 14.32499f },
	{ 24.132f, -9.981002f, 35.83799f },
	{ 14.769f, -5.697f, 58.7f },
	{ 9.0659f, -3.287999f, 68.17499f },
	{ 5.659f, -2.9f, 70.22499f },
	{ -5.506f, -2.9f, 70.22499f },
	{ -9.0328f, -3.287999f, 68.17499f },
	{ 20.552f, -12.75f, 36.081f },
	{ 17.883f, -16.294f, 35.344f },
	{ -20.552f, -12.75f, 36.06f },
	{ -17.883f, -16.294f, 35.344f },
	{ 12.744f, 13.08801f, 46.694f },
	{ -12.844f, 13.08801f, 46.694f },
	{ 19.051f, 2.643997f, 46.694f },
	{ -19.051f, 2.643997f, 46.694f },
	{ -19.451f, -7.939001f, 46.76899f },
	{ -18.126f, -10.7f, 46.594f },
	{ 19.45f, -7.939061f, 46.76899f },
	{ 18.126f, -10.7f, 46.594f }
};

NJS_VECTOR normal_00147BDC[] = {
	{ 0.086283f, -0.948913f, -0.303513f },
	{ 0.728882f, -0.265972f, 0.630865f },
	{ -0.44716f, -0.564744f, 0.693622f },
	{ 0.34778f, 0.099278f, -0.932305f },
	{ -0.086283f, -0.948913f, -0.303513f },
	{ -0.728882f, -0.265972f, 0.630865f },
	{ 0.44716f, -0.564744f, 0.693622f },
	{ -0.34778f, 0.099278f, -0.932305f },
	{ 0.855802f, 0.392008f, 0.337539f },
	{ 0.129643f, 0.974037f, 0.185593f },
	{ 0.396747f, 0.877215f, 0.270343f },
	{ 0.448783f, 0.827091f, -0.338399f },
	{ 0.621368f, 0.7724659f, -0.131144f },
	{ 0.783157f, 0.3535f, -0.511569f },
	{ 0.867636f, 0.410288f, -0.28084f },
	{ 0.947176f, -0.153698f, -0.281487f },
	{ 0.993961f, 0.009513999f, -0.109323f },
	{ 0.870952f, -0.44379f, 0.210934f },
	{ 0.935866f, -0.213986f, 0.279936f },
	{ 0.585212f, -0.358365f, 0.727394f },
	{ 0.721676f, -0.132068f, 0.679516f },
	{ 0.23417f, 0.09850699f, 0.967192f },
	{ 0.470022f, 0.225251f, 0.853429f },
	{ 0.037118f, 0.66704f, 0.744096f },
	{ 0.333082f, 0.648885f, 0.684108f },
	{ -0.855805f, 0.391976f, 0.33757f },
	{ -0.1294f, 0.974067f, 0.185604f },
	{ -0.396634f, 0.877284f, 0.270284f },
	{ -0.448244f, 0.8272499f, -0.338727f },
	{ -0.621319f, 0.77246f, -0.131407f },
	{ -0.782665f, 0.353318f, -0.512448f },
	{ -0.867559f, 0.410076f, -0.281389f },
	{ -0.946798f, -0.154474f, -0.282333f },
	{ -0.99391f, 0.009044999f, -0.10982f },
	{ -0.870501f, -0.444789f, 0.21069f },
	{ -0.935784f, -0.214582f, 0.279753f },
	{ -0.5846649f, -0.358902f, 0.727569f },
	{ -0.7215469f, -0.13247f, 0.679575f },
	{ -0.233846f, 0.09846999f, 0.967274f },
	{ -0.469939f, 0.225104f, 0.853514f },
	{ -0.037066f, 0.667054f, 0.744087f },
	{ -0.333058f, 0.648876f, 0.684129f },
	{ 0.735934f, 0.299948f, -0.606986f },
	{ 0.925469f, 0.377197f, 0.035049f },
	{ -0.070205f, 0.990393f, 0.119137f },
	{ -0.06408899f, 0.9041139f, -0.422459f },
	{ -0.772586f, 0.193147f, -0.604818f },
	{ -0.969386f, 0.242347f, 0.039477f },
	{ -0.735934f, 0.299948f, -0.606986f },
	{ -0.925469f, 0.377197f, 0.035049f },
	{ 0.070205f, 0.990393f, 0.119137f },
	{ 0.06408899f, 0.9041139f, -0.422459f },
	{ 0.772586f, 0.193147f, -0.604818f },
	{ 0.969386f, 0.242347f, 0.039477f },
	{ -0.491218f, 0.661184f, -0.567045f },
	{ -0.6555f, 0.753089f, 0.056364f },
	{ 0.489017f, 0.662985f, -0.566845f },
	{ 0.6523319f, 0.755819f, 0.056568f },
	{ -0.901862f, -0.431702f, 0.016673f },
	{ -0.749441f, -0.297967f, -0.59123f },
	{ 0.750012f, -0.29609f, -0.591449f },
	{ 0.903152f, -0.429033f, 0.015724f },
	{ -0.000502f, -0.8000529f, -0.59993f },
	{ -0.000548f, -0.999957f, 0.009237f },
	{ -0.299165f, -0.857521f, -0.418519f },
	{ -0.503682f, -0.855152f, -0.122556f },
	{ -0.310094f, -0.786689f, -0.533819f },
	{ -0.802185f, -0.580857f, -0.13822f },
	{ 0.193424f, -0.910086f, -0.366512f },
	{ 0.408571f, -0.907891f, -0.09382799f },
	{ 0.202216f, -0.854379f, -0.478691f },
	{ 0.689481f, -0.7174f, -0.099767f },
	{ -0.26541f, -0.70016f, 0.662823f },
	{ -0.289118f, -0.520995f, 0.803104f },
	{ 0.265389f, -0.700159f, 0.662832f },
	{ 0.289097f, -0.520995f, 0.803111f },
	{ -0.286787f, -0.730698f, -0.619543f },
	{ -0.5422249f, -0.833596f, -0.105397f },
	{ -0.333688f, 0.792565f, -0.510385f },
	{ -0.522159f, 0.846766f, -0.101679f },
	{ 0.286787f, -0.730698f, -0.619543f },
	{ 0.5422249f, -0.833596f, -0.105397f },
	{ 0.333688f, 0.792565f, -0.510385f },
	{ 0.522159f, 0.846765f, -0.101679f },
	{ -0.481702f, -0.772067f, 0.414579f },
	{ -0.425483f, 0.812683f, 0.398134f },
	{ 0.48201f, -0.77222f, 0.413935f },
	{ 0.425797f, 0.812885f, 0.397386f },
	{ -0.37104f, -0.678805f, 0.633683f },
	{ -0.257513f, 0.133073f, 0.957068f },
	{ 0.373536f, -0.6800449f, 0.63088f },
	{ 0.24992f, 0.133997f, 0.95895f },
	{ 0.375456f, 0.6774769f, 0.6325009f },
	{ -0.378183f, 0.676722f, 0.6316839f },
	{ 0.498113f, -0.840727f, 0.212279f },
	{ 0.487073f, 0.857505f, 0.165663f },
	{ -0.4863f, 0.858146f, 0.164613f },
	{ -0.498116f, -0.840727f, 0.21227f },
	{ 0.70272f, -0.488212f, 0.517527f },
	{ -0.702839f, -0.488139f, 0.517433f },
	{ -0.420688f, -0.8111759f, 0.406221f },
	{ 0.420599f, -0.81121f, 0.406246f },
	{ 0.741335f, 0.184831f, 0.645182f },
	{ 0.864924f, 0.28045f, 0.416237f },
	{ 0.932025f, 0.27241f, 0.239001f },
	{ 0.952002f, 0.279773f, -0.124173f },
	{ 0.537618f, 0.25717f, -0.803013f },
	{ -0.537618f, 0.25717f, -0.803013f },
	{ -0.952002f, 0.279773f, -0.124173f },
	{ -0.932193f, 0.272527f, 0.238213f },
	{ -0.864202f, 0.28f, 0.418037f },
	{ -0.743377f, 0.181126f, 0.643882f },
	{ -0.872136f, -0.161249f, 0.461928f },
	{ -0.9325809f, -0.240629f, 0.269054f },
	{ -0.96363f, -0.23163f, -0.133287f },
	{ -0.5714869f, -0.225256f, -0.78909f },
	{ 0.5714869f, -0.225256f, -0.78909f },
	{ 0.96363f, -0.23163f, -0.133287f },
	{ 0.932578f, -0.240625f, 0.269069f },
	{ 0.873126f, -0.161593f, 0.459933f },
	{ 0.710102f, -0.160151f, 0.685644f },
	{ 0.241008f, -0.410109f, 0.879617f },
	{ -0.237066f, -0.414898f, 0.878442f },
	{ -0.708197f, -0.160699f, 0.687483f },
	{ 0.794617f, -0.546405f, 0.264624f },
	{ 0.462914f, -0.8618f, 0.207392f },
	{ -0.794957f, -0.54611f, 0.264212f },
	{ -0.46313f, -0.861637f, 0.207587f },
	{ 0.439104f, 0.829816f, 0.344374f },
	{ -0.440951f, 0.828832f, 0.344383f },
	{ 0.88332f, 0.27982f, 0.376094f },
	{ -0.883419f, 0.279893f, 0.375807f },
	{ -0.895898f, -0.191961f, 0.400647f },
	{ -0.469691f, -0.81379f, 0.342252f },
	{ 0.895898f, -0.19196f, 0.400648f },
	{ 0.46969f, -0.81379f, 0.342253f }
};

NJS_MODEL_SADX attach_0014823C = { vertex_0014757C, normal_00147BDC, LengthOfArray(vertex_0014757C), meshlist_0014730C, matlist_00146668, LengthOfArray(meshlist_0014730C), LengthOfArray(matlist_00146668),{ 0, 0.45f, 26.81249f }, 51.9069f, NULL };

NJS_OBJECT object_00148264 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_0014823C, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Snake joint


NJS_MATERIAL matlist_00148EAC[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw017, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw023, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00148F24[] = {
	0x8000u | 5, 1, 2, 3, 5, 4,
	3, 1, 0, 3,
	0x8000u | 5, 6, 9, 8, 10, 11,
	3, 6, 7, 8
};

Sint16 poly_00148F4C[] = {
	3, 2, 5, 1,
	3, 3, 0, 4,
	3, 7, 11, 8,
	3, 10, 6, 9
};

Sint16 poly_00148F6C[] = {
	0x8000u | 6, 18, 17, 21, 12, 19, 20
};

Sint16 poly_00148F7A[] = {
	4, 16, 15, 14, 13
};

Sint16 poly_00148F84[] = {
	4, 13, 18, 14, 17,
	4, 16, 20, 15, 19
};

Sint16 poly_00148F98[] = {
	3, 17, 12, 20,
	4, 14, 17, 16, 20,
	3, 19, 21, 18,
	4, 15, 19, 13, 18
};

NJS_TEX uv_00148FBC[] = {
	{ 1530, 216 },
	{ 1530, 7 },
	{ 0, 7 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 0, 7 },
	{ 0, 215 },
	{ 0, 7 },
	{ 1530, 7 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 1530, 7 }
};

NJS_TEX uv_00148FFC[] = {
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 }
};

NJS_TEX uv_0014902C[] = {
	{ 0, 255 },
	{ 0, -510 },
	{ 251, 255 },
	{ 251, -510 },
	{ 0, 255 },
	{ 0, -510 }
};

NJS_TEX uv_00149044[] = {
	{ 253, 255 },
	{ 253, -255 },
	{ 0, 255 },
	{ 0, -255 }
};

NJS_TEX uv_00149054[] = {
	{ 510, 255 },
	{ 510, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 510, 255 },
	{ 510, -254 }
};

NJS_TEX uv_00149074[] = {
	{ 510, -254 },
	{ 270, 256 },
	{ 0, -254 },
	{ 510, -254 },
	{ 510, 255 },
	{ 0, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 270, 256 },
	{ 510, -254 },
	{ 0, -254 },
	{ 0, 255 },
	{ 510, -254 },
	{ 510, 255 }
};

NJS_MESHSET_SADX meshlist_001490AC[] = {
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00148F24, NULL, NULL, NULL, uv_00148FBC, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 4, poly_00148F4C, NULL, NULL, NULL, uv_00148FFC, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 1, poly_00148F6C, NULL, NULL, NULL, uv_0014902C, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 1, poly_00148F7A, NULL, NULL, NULL, uv_00149044, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_00148F84, NULL, NULL, NULL, uv_00149054, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 4, poly_00148F98, NULL, NULL, NULL, uv_00149074, NULL }
};

NJS_VECTOR vertex_0014913C[] = {
	{ -10.21415f, 15.13826f, -17.49999f },
	{ -12, 15, 17.5f },
	{ -13, 19, 17.5f },
	{ -11.06533f, 18.48179f, -17.49999f },
	{ -11.91651f, 15.13826f, -17.49999f },
	{ -14, 15, 17.5f },
	{ 10.21415f, 15.13826f, -17.49999f },
	{ 12, 15, 17.5f },
	{ 13, 19, 17.5f },
	{ 11.06533f, 18.48179f, -17.49999f },
	{ 11.91652f, 15.13826f, -17.49999f },
	{ 14, 15, 17.5f },
	{ 0, -18.1f, 17.5f },
	{ -12.12932f, 15.15916f, -17.49999f },
	{ -14.25f, 15.025f, 17.5f },
	{ 12.12932f, 15.15916f, -17.49999f },
	{ 14.25f, 15.025f, 17.5f },
	{ -19.5f, -5.6f, 17.5f },
	{ -16.59802f, -2.08095f, -17.49999f },
	{ 16.59802f, -2.08095f, -17.49999f },
	{ 19.5f, -5.6f, 17.5f },
	{ 0, -12.5295f, -17.49999f }
};

NJS_VECTOR normal_00149244[] = {
	{ 0.75842f, 0.191185f, -0.623096f },
	{ 0.7239799f, 0.182503f, 0.66524f },
	{ -0.027179f, 0.847034f, 0.530844f },
	{ 0.029942f, 0.837028f, -0.54634f },
	{ -0.723967f, 0.184305f, -0.664758f },
	{ -0.757332f, 0.192799f, 0.62392f },
	{ -0.75842f, 0.191185f, -0.623096f },
	{ -0.723981f, 0.182503f, 0.66524f },
	{ 0.027179f, 0.847033f, 0.530844f },
	{ -0.029942f, 0.837028f, -0.54634f },
	{ 0.723967f, 0.184305f, -0.664758f },
	{ 0.757332f, 0.192799f, 0.62392f },
	{ 0, -0.837874f, 0.545864f },
	{ -0.475578f, 0.639033f, -0.604535f },
	{ -0.512381f, 0.634993f, 0.5781429f },
	{ 0.475578f, 0.639033f, -0.604535f },
	{ 0.512381f, 0.634993f, 0.5781429f },
	{ -0.767826f, -0.323526f, 0.552968f },
	{ -0.723708f, -0.265708f, -0.636903f },
	{ 0.723708f, -0.265708f, -0.636903f },
	{ 0.767826f, -0.323526f, 0.552968f },
	{ 0, -0.7500269f, -0.6614079f }
};

NJS_MODEL_SADX attach_0014934C = { vertex_0014913C, normal_00149244, LengthOfArray(vertex_0014913C), meshlist_001490AC, matlist_00148EAC, LengthOfArray(meshlist_001490AC), LengthOfArray(matlist_00148EAC),{ 0, 0.449999f, 0.000004f }, 26.20114f, NULL };

NJS_OBJECT object_00149374 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_0014934C, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Fire barrier


NJS_MATERIAL matlist_00149BEC[] = {
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_m128_los037, NJD_D_100 | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_lost1_27, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_ama_lw055, NJD_D_100 | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00149C28[] = {
	4, 3, 2, 1, 0,
	4, 7, 3, 5, 1,
	4, 6, 7, 4, 5,
	4, 2, 6, 0, 4
};

Sint16 poly_00149C50[] = {
	4, 8, 10, 2, 6,
	4, 9, 8, 3, 2,
	4, 11, 9, 7, 3,
	4, 10, 11, 6, 7
};

Sint16 poly_00149C78[] = {
	4, 11, 10, 9, 8
};

NJS_TEX uv_00149C84[] = {
	{ 253, -255 },
	{ 0, -255 },
	{ 253, 255 },
	{ 0, 255 },
	{ 253, -255 },
	{ 0, -255 },
	{ 253, 255 },
	{ 0, 255 },
	{ 253, -255 },
	{ 0, -255 },
	{ 253, 255 },
	{ 0, 255 },
	{ 253, -255 },
	{ 0, -255 },
	{ 253, 255 },
	{ 0, 255 }
};

NJS_TEX uv_00149CC4[] = {
	{ 507, 5 },
	{ 0, 5 },
	{ 506, 134 },
	{ 1, 133 },
	{ 507, 5 },
	{ 0, 5 },
	{ 506, 134 },
	{ 1, 133 },
	{ 507, 5 },
	{ 0, 5 },
	{ 506, 134 },
	{ 1, 133 },
	{ 507, 5 },
	{ 0, 5 },
	{ 506, 134 },
	{ 1, 133 }
};

NJS_TEX uv_00149D04[] = {
	{ 0, 255 },
	{ 0, -255 },
	{ 510, 255 },
	{ 510, -255 }
};

NJS_MESHSET_SADX meshlist_00149D14[] = {
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00149C28, NULL, NULL, NULL, uv_00149C84, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 4, poly_00149C50, NULL, NULL, NULL, uv_00149CC4, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 1, poly_00149C78, NULL, NULL, NULL, uv_00149D04, NULL }
};

NJS_VECTOR vertex_00149D5C[] = {
	{ -10, -36.99999f, -10 },
	{ -10, -36.99999f, 10 },
	{ -10, 0.000006f, -10 },
	{ -10, 0.000006f, 10 },
	{ 10, -36.99999f, -10 },
	{ 10, -36.99999f, 10 },
	{ 10, 0.000006f, -10 },
	{ 10, 0.000006f, 10 },
	{ -9.599999f, 3.000006f, -9.599999f },
	{ -9.599999f, 3.000006f, 9.599999f },
	{ 9.599999f, 3.000006f, -9.599999f },
	{ 9.599999f, 3.000006f, 9.599999f }
};

NJS_VECTOR normal_00149DEC[] = {
	{ -0.7071069f, 0, -0.7071069f },
	{ -0.7071069f, 0, 0.7071069f },
	{ -0.704276f, 0.08939099f, -0.704276f },
	{ -0.704276f, 0.08939099f, 0.704276f },
	{ 0.7071069f, 0, -0.7071069f },
	{ 0.7071069f, 0, 0.7071069f },
	{ 0.704276f, 0.08939099f, -0.704276f },
	{ 0.704276f, 0.08939099f, 0.704276f },
	{ -0.5396079f, 0.646255f, -0.5396079f },
	{ -0.5396079f, 0.646255f, 0.5396079f },
	{ 0.5396079f, 0.646255f, -0.5396079f },
	{ 0.5396079f, 0.646255f, 0.5396079f }
};

NJS_MODEL_SADX attach_00149E7C = { vertex_00149D5C, normal_00149DEC, LengthOfArray(vertex_00149D5C), meshlist_00149D14, matlist_00149BEC, LengthOfArray(meshlist_00149D14), LengthOfArray(matlist_00149BEC),{ 0, -16.99999f, 0 }, 22.36068f, NULL };

NJS_OBJECT object_00149EA4 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_00149E7C, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Snake stuff

NJS_MATERIAL matlist_001489B0[] = {
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_ama_lw017, NJD_D_100 | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0x00000000 }, 0, OBJ_RUINTexName_ama_lw023, NJD_D_100 | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00148A28[] = {
	0x8000u | 5, 1, 2, 3, 5, 4,
	3, 1, 0, 3,
	0x8000u | 5, 6, 9, 8, 10, 11,
	3, 6, 7, 8
};

Sint16 poly_00148A50[] = {
	3, 2, 5, 1,
	3, 3, 0, 4,
	3, 7, 11, 8,
	3, 10, 6, 9
};

Sint16 poly_00148A70[] = {
	0x8000u | 6, 18, 17, 21, 12, 19, 20
};

Sint16 poly_00148A7E[] = {
	4, 16, 15, 14, 13
};

Sint16 poly_00148A88[] = {
	4, 13, 18, 14, 17,
	4, 16, 20, 15, 19
};

Sint16 poly_00148A9C[] = {
	3, 17, 12, 20,
	4, 14, 17, 16, 20,
	3, 19, 21, 18,
	4, 15, 19, 13, 18
};

NJS_TEX uv_00148AC0[] = {
	{ 1530, 216 },
	{ 1530, 7 },
	{ 0, 7 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 0, 7 },
	{ 0, 215 },
	{ 0, 7 },
	{ 1530, 7 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 1530, 7 }
};

NJS_TEX uv_00148B00[] = {
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 }
};

NJS_TEX uv_00148B30[] = {
	{ 0, 255 },
	{ 0, -510 },
	{ 251, 255 },
	{ 251, -510 },
	{ 0, 255 },
	{ 0, -510 }
};

NJS_TEX uv_00148B48[] = {
	{ 253, 255 },
	{ 253, -255 },
	{ 0, 255 },
	{ 0, -255 }
};

NJS_TEX uv_00148B58[] = {
	{ 510, 255 },
	{ 510, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 510, 255 },
	{ 510, -254 }
};

NJS_TEX uv_00148B78[] = {
	{ 510, -254 },
	{ 270, 256 },
	{ 0, -254 },
	{ 510, -254 },
	{ 510, 255 },
	{ 0, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 270, 256 },
	{ 510, -254 },
	{ 0, -254 },
	{ 0, 255 },
	{ 510, -254 },
	{ 510, 255 }
};

NJS_MESHSET_SADX meshlist_00148BB0[] = {
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00148A28, NULL, NULL, NULL, uv_00148AC0, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 4, poly_00148A50, NULL, NULL, NULL, uv_00148B00, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 1, poly_00148A70, NULL, NULL, NULL, uv_00148B30, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 1, poly_00148A7E, NULL, NULL, NULL, uv_00148B48, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_00148A88, NULL, NULL, NULL, uv_00148B58, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 4, poly_00148A9C, NULL, NULL, NULL, uv_00148B78, NULL }
};

NJS_VECTOR vertex_00148C40[] = {
	{ -11.99999f, 15, -17.49999f },
	{ -12, 15, 17.5f },
	{ -13, 19, 17.5f },
	{ -12.99999f, 19, -17.49999f },
	{ -13.99999f, 15, -17.49999f },
	{ -14, 15, 17.5f },
	{ 12, 15, -17.49999f },
	{ 12, 15, 17.5f },
	{ 13, 19, 17.5f },
	{ 13, 19, -17.49999f },
	{ 14, 15, -17.49999f },
	{ 14, 15, 17.5f },
	{ 0, -18.1f, 17.5f },
	{ -14.25f, 15.025f, -17.49999f },
	{ -14.25f, 15.025f, 17.5f },
	{ 14.25f, 15.025f, -17.49999f },
	{ 14.25f, 15.025f, 17.5f },
	{ -19.5f, -5.6f, 17.5f },
	{ -19.5f, -5.6f, -17.49999f },
	{ 19.5f, -5.6f, -17.49999f },
	{ 19.5f, -5.6f, 17.5f },
	{ 0, -18.1f, -17.49999f }
};

NJS_VECTOR normal_00148D48[] = {
	{ 0.741365f, 0.185341f, -0.645001f },
	{ 0.741365f, 0.185341f, 0.645001f },
	{ 0, 0.8411109f, 0.540862f },
	{ 0, 0.8411109f, -0.540862f },
	{ -0.741365f, 0.185341f, -0.645001f },
	{ -0.741365f, 0.185341f, 0.645001f },
	{ -0.741365f, 0.185341f, -0.645001f },
	{ -0.741365f, 0.185341f, 0.645001f },
	{ 0, 0.8411109f, 0.540862f },
	{ 0, 0.8411109f, -0.540862f },
	{ 0.741365f, 0.185341f, -0.645001f },
	{ 0.741365f, 0.185341f, 0.645001f },
	{ 0, -0.7974049f, 0.603445f },
	{ -0.494805f, 0.636534f, -0.591602f },
	{ -0.494805f, 0.636534f, 0.591602f },
	{ 0.494805f, 0.636534f, -0.591602f },
	{ 0.494805f, 0.636534f, 0.591602f },
	{ -0.746878f, -0.29464f, 0.596121f },
	{ -0.746878f, -0.29464f, -0.596121f },
	{ 0.746878f, -0.29464f, -0.596121f },
	{ 0.746878f, -0.29464f, 0.596121f },
	{ 0, -0.7974049f, -0.603445f }
};

NJS_MODEL_SADX attach_00148E50 = { vertex_00148C40, normal_00148D48, LengthOfArray(vertex_00148C40), meshlist_00148BB0, matlist_001489B0, LengthOfArray(meshlist_00148BB0), LengthOfArray(matlist_001489B0),{ 0, 0.449999f, 0.000004f }, 26.20114f, NULL };

NJS_OBJECT object_00148E78 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_00148E50, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

NJS_MATERIAL matlist_001493A8[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw017, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw023, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00149420[] = {
	0x8000u | 5, 1, 2, 3, 5, 4,
	3, 1, 0, 3,
	0x8000u | 5, 6, 9, 8, 10, 11,
	3, 6, 7, 8
};

Sint16 poly_00149448[] = {
	3, 2, 5, 1,
	3, 3, 0, 4,
	3, 7, 11, 8,
	3, 10, 6, 9
};

Sint16 poly_00149468[] = {
	0x8000u | 6, 20, 19, 12, 21, 17, 18
};

Sint16 poly_00149476[] = {
	4, 16, 15, 14, 13
};

Sint16 poly_00149480[] = {
	4, 13, 18, 14, 17,
	4, 16, 20, 15, 19
};

Sint16 poly_00149494[] = {
	3, 17, 12, 20,
	4, 14, 17, 16, 20,
	3, 19, 21, 18,
	4, 15, 19, 13, 18
};

NJS_TEX uv_001494B8[] = {
	{ 1530, 216 },
	{ 1530, 7 },
	{ 0, 7 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 0, 7 },
	{ 0, 215 },
	{ 0, 7 },
	{ 1530, 7 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 0, 215 },
	{ 1530, 216 },
	{ 1530, 7 }
};

NJS_TEX uv_001494F8[] = {
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 }
};

NJS_TEX uv_00149528[] = {
	{ 0, -510 },
	{ 0, 255 },
	{ 251, -510 },
	{ 251, 255 },
	{ 0, -510 },
	{ 0, 255 }
};

NJS_TEX uv_00149540[] = {
	{ 253, 255 },
	{ 253, -255 },
	{ 0, 255 },
	{ 0, -255 }
};

NJS_TEX uv_00149550[] = {
	{ 0, 255 },
	{ 0, -254 },
	{ 510, 255 },
	{ 510, -254 },
	{ 510, 255 },
	{ 510, -254 },
	{ 0, 255 },
	{ 0, -254 }
};

NJS_TEX uv_00149570[] = {
	{ 510, -254 },
	{ 270, 256 },
	{ 0, -254 },
	{ 510, -254 },
	{ 510, 255 },
	{ 0, -254 },
	{ 0, 255 },
	{ 0, -254 },
	{ 270, 256 },
	{ 510, -254 },
	{ 0, -254 },
	{ 0, 255 },
	{ 510, -254 },
	{ 510, 255 }
};

NJS_MESHSET_SADX meshlist_001495A8[] = {
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00149420, NULL, NULL, NULL, uv_001494B8, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 4, poly_00149448, NULL, NULL, NULL, uv_001494F8, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 1, poly_00149468, NULL, NULL, NULL, uv_00149528, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 1, poly_00149476, NULL, NULL, NULL, uv_00149540, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_00149480, NULL, NULL, NULL, uv_00149550, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 4, poly_00149494, NULL, NULL, NULL, uv_00149570, NULL }
};

NJS_VECTOR vertex_00149638[] = {
	{ 10.21415f, 15.33826f, 17.49999f },
	{ 7.800004f, 15.22201f, -17.5f },
	{ 8.450003f, 17.68121f, -17.5f },
	{ 11.06533f, 18.68179f, 17.49999f },
	{ 11.91651f, 15.33826f, 17.49999f },
	{ 9.1f, 15.22201f, -17.5f },
	{ -10.21415f, 15.33826f, 17.49999f },
	{ -7.800007f, 15.22201f, -17.5f },
	{ -8.450004f, 17.68121f, -17.5f },
	{ -11.06533f, 18.68179f, 17.49999f },
	{ -11.91652f, 15.33826f, 17.49999f },
	{ -9.1f, 15.22201f, -17.5f },
	{ -0.00001f, -5.127892f, -17.5f },
	{ 12.12932f, 15.35916f, 17.49999f },
	{ 9.2625f, 15.23737f, -17.5f },
	{ -12.12932f, 15.35916f, 17.49999f },
	{ -9.262505f, 15.23737f, -17.5f },
	{ 12.67501f, 2.55712f, -17.5f },
	{ 16.59802f, -1.88095f, 17.49999f },
	{ -16.59802f, -1.88095f, 17.49999f },
	{ -12.67501f, 2.55712f, -17.5f },
	{ 0.000001f, -12.32951f, 17.49999f }
};

NJS_VECTOR normal_00149740[] = {
	{ -0.720184f, 0.186313f, 0.6682979f },
	{ -0.762411f, 0.197237f, -0.6163009f },
	{ -0.038379f, 0.828263f, -0.559023f },
	{ 0.039463f, 0.8485759f, 0.5276f },
	{ 0.766428f, 0.195114f, 0.6119789f },
	{ 0.7174169f, 0.182637f, -0.672277f },
	{ 0.720185f, 0.186313f, 0.6682979f },
	{ 0.762411f, 0.197237f, -0.616302f },
	{ 0.038379f, 0.828263f, -0.559023f },
	{ -0.039464f, 0.8485759f, 0.5276f },
	{ -0.766428f, 0.195114f, 0.6119789f },
	{ -0.7174169f, 0.182637f, -0.672277f },
	{ 0, -0.733607f, -0.679574f },
	{ 0.516336f, 0.638315f, 0.570922f },
	{ 0.466756f, 0.638221f, -0.612219f },
	{ -0.516336f, 0.638315f, 0.570922f },
	{ -0.466757f, 0.638221f, -0.612219f },
	{ 0.715881f, -0.260214f, -0.647922f },
	{ 0.774067f, -0.332713f, 0.5386299f },
	{ -0.774067f, -0.332713f, 0.5386299f },
	{ -0.715881f, -0.260214f, -0.647922f },
	{ 0, -0.847577f, 0.530673f }
};

NJS_MODEL_SADX attach_00149848 = { vertex_00149638, normal_00149740, LengthOfArray(vertex_00149638), meshlist_001495A8, matlist_001493A8, LengthOfArray(meshlist_001495A8), LengthOfArray(matlist_001493A8),{ 0.000002f, 3.176144f, -0.00004f }, 24.11937f, NULL };

NJS_OBJECT object_00149870 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_00149848, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };
NJS_MATERIAL matlist_00148298[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw021, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw017, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_lost1_26, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw020, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_RUINTexName_ama_lw023, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00148310[] = {
	0x8000u | 5, 1, 2, 3, 5, 4,
	3, 1, 0, 3,
	0x8000u | 5, 6, 9, 8, 10, 11,
	3, 6, 7, 8
};

Sint16 poly_00148338[] = {
	3, 2, 5, 1,
	3, 3, 0, 4,
	3, 7, 11, 8,
	3, 10, 6, 9
};

Sint16 poly_00148358[] = {
	0x8000u | 6, 18, 17, 21, 12, 19, 20,
	4, 19, 21, 22, 18
};

Sint16 poly_00148370[] = {
	4, 16, 15, 14, 13,
	3, 22, 13, 15
};

Sint16 poly_00148382[] = {
	4, 13, 18, 14, 17,
	4, 16, 20, 15, 19,
	3, 15, 19, 22,
	3, 22, 18, 13
};

Sint16 poly_001483A6[] = {
	3, 17, 12, 20,
	4, 14, 17, 16, 20
};

NJS_TEX uv_001483B8[] = {
	{ 2550, 216 },
	{ 2550, 7 },
	{ 0, 7 },
	{ 2550, 216 },
	{ 0, 215 },
	{ 2550, 216 },
	{ 0, 215 },
	{ 0, 7 },
	{ 0, 215 },
	{ 0, 7 },
	{ 2550, 7 },
	{ 0, 215 },
	{ 2550, 216 },
	{ 0, 215 },
	{ 2550, 216 },
	{ 2550, 7 }
};

NJS_TEX uv_001483F8[] = {
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 },
	{ 136, 208 },
	{ 247, 208 },
	{ 195, 7 }
};

NJS_TEX uv_00148428[] = {
	{ 31, -510 },
	{ 0, 255 },
	{ 251, -510 },
	{ 251, 255 },
	{ 31, -510 },
	{ 0, 255 },
	{ 4, 255 },
	{ 189, 255 },
	{ 189, -506 },
	{ 4, 255 }
};

NJS_TEX uv_00148450[] = {
	{ 221, 255 },
	{ 179, -762 },
	{ 32, 255 },
	{ 78, -762 },
	{ 125, -762 },
	{ 64, 255 },
	{ 188, 255 }
};

NJS_TEX uv_0014846C[] = {
	{ 765, 255 },
	{ 765, -66 },
	{ 0, 255 },
	{ -1, -147 },
	{ 0, 255 },
	{ -1, -147 },
	{ 765, 255 },
	{ 765, -66 },
	{ 0, 255 },
	{ 0, -61 },
	{ 765, 255 },
	{ 765, 255 },
	{ 0, -61 },
	{ 0, 255 }
};

NJS_TEX uv_001484A4[] = {
	{ 510, -254 },
	{ 270, 256 },
	{ 0, -254 },
	{ 510, -254 },
	{ 510, 255 },
	{ 0, -254 },
	{ 0, 255 }
};

NJS_MESHSET_SADX meshlist_001484C0[] = {
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00148310, NULL, NULL, NULL, uv_001483B8, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 4, poly_00148338, NULL, NULL, NULL, uv_001483F8, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_00148358, NULL, NULL, NULL, uv_00148428, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 2, poly_00148370, NULL, NULL, NULL, uv_00148450, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 4, poly_00148382, NULL, NULL, NULL, uv_0014846C, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 2, poly_001483A6, NULL, NULL, NULL, uv_001484A4, NULL }
};

NJS_VECTOR vertex_00148550[] = {
	{ -4.220368f, 15.0234f, -29.69994f },
	{ -7.90512f, 15.0276f, 17.4f },
	{ -8.56774f, 17.53045f, 17.4f },
	{ -4.571153f, 16.233f, -29.69994f },
	{ -4.921937f, 15.0234f, -29.69994f },
	{ -9.243627f, 15.0276f, 17.4f },
	{ 4.220368f, 15.0234f, -29.69994f },
	{ 7.90512f, 15.0276f, 17.4f },
	{ 8.56774f, 17.53045f, 17.4f },
	{ 4.571153f, 16.233f, -29.69994f },
	{ 4.921937f, 15.0234f, -29.69994f },
	{ 9.243627f, 15.0276f, 17.4f },
	{ 0, -5.765293f, 17.4f },
	{ -5.009634f, 15.036f, -29.69994f },
	{ -9.3894f, 15.0276f, 17.4f },
	{ 5.009634f, 15.036f, -29.69994f },
	{ 9.3894f, 15.0276f, 17.4f },
	{ -12.8483f, 2.084834f, 17.4f },
	{ -6.851247f, 8.811602f, -29.69994f },
	{ 6.851247f, 8.811602f, -29.69994f },
	{ 12.8483f, 2.084834f, 17.4f },
	{ 0, 5.031602f, -29.69994f },
	{ 0, 14.82f, -77.7f }
};

NJS_VECTOR normal_00148664[] = {
	{ 0.768513f, 0.209785f, -0.6044649f },
	{ 0.716166f, 0.195495f, 0.669991f },
	{ -0.034713f, 0.857812f, 0.51279f },
	{ 0.051509f, 0.82793f, -0.558461f },
	{ -0.714202f, 0.207119f, -0.6685939f },
	{ -0.764837f, 0.221803f, 0.604836f },
	{ -0.768513f, 0.209785f, -0.6044649f },
	{ -0.716166f, 0.195495f, 0.669991f },
	{ 0.034713f, 0.857812f, 0.51279f },
	{ -0.051509f, 0.82793f, -0.558461f },
	{ 0.714202f, 0.207119f, -0.6685939f },
	{ 0.764837f, 0.221803f, 0.604836f },
	{ 0, -0.852654f, 0.5224749f },
	{ -0.600423f, 0.797357f, -0.060944f },
	{ -0.515663f, 0.640423f, 0.569167f },
	{ 0.600423f, 0.797357f, -0.060944f },
	{ 0.515663f, 0.640423f, 0.569167f },
	{ -0.775452f, -0.340661f, 0.531625f },
	{ -0.91537f, -0.363372f, -0.173376f },
	{ 0.91537f, -0.363372f, -0.173376f },
	{ 0.775452f, -0.340661f, 0.531625f },
	{ 0, -0.978387f, -0.206782f },
	{ 0, 0.085297f, -0.996356f }
};

NJS_MODEL_SADX attach_00148778 = { vertex_00148550, normal_00148664, LengthOfArray(vertex_00148550), meshlist_001484C0, matlist_00148298, LengthOfArray(meshlist_001484C0), LengthOfArray(matlist_00148298),{ 0, 5.882578f, -30.15f }, 49.25526f, NULL };

NJS_OBJECT object_001487A0 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_00148778, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };
