/* NINJA Basic (with Sonic Adventure DX additions) model
*
* Generated by SAMDL
*
*/

enum OBJ_FINALEGGTexName
{
	OBJ_FINALEGGTexName_d64arm4f,
	OBJ_FINALEGGTexName_d64metal1f,
	OBJ_FINALEGGTexName_d64metal2f,
	OBJ_FINALEGGTexName_d64tunagi1f,
	OBJ_FINALEGGTexName_tm128dak,
	OBJ_FINALEGGTexName_tm16sya,
	OBJ_FINALEGGTexName_tm16cam,
	OBJ_FINALEGGTexName_tm32gars,
	OBJ_FINALEGGTexName_tm64ginp,
	OBJ_FINALEGGTexName_tm64green,
	OBJ_FINALEGGTexName_tm64grnx,
	OBJ_FINALEGGTexName_tm64limo,
	OBJ_FINALEGGTexName_tm128tec,
	OBJ_FINALEGGTexName_fq64mtl_base01,
	OBJ_FINALEGGTexName_tm128gateja,
	OBJ_FINALEGGTexName_tm128keiki2,
	OBJ_FINALEGGTexName_d16jet1alfa,
	OBJ_FINALEGGTexName_tym64bkl,
	OBJ_FINALEGGTexName_tm16beam3,
	OBJ_FINALEGGTexName_d64_lv1_1c,
	OBJ_FINALEGGTexName_tm32bk1,
	OBJ_FINALEGGTexName_tm32gars2,
	OBJ_FINALEGGTexName_tm16yel,
	OBJ_FINALEGGTexName_tm64objgr1,
	OBJ_FINALEGGTexName_tm64objgr2,
	OBJ_FINALEGGTexName_tm128keiki,
	OBJ_FINALEGGTexName_d64tunagi5f,
	OBJ_FINALEGGTexName_fq128wall21,
	OBJ_FINALEGGTexName_fq64sabi02,
	OBJ_FINALEGGTexName_d128_lv1_1b,
	OBJ_FINALEGGTexName_tm128saba,
	OBJ_FINALEGGTexName_tm16beam2,
	OBJ_FINALEGGTexName_tm16bkbk,
	OBJ_FINALEGGTexName_tm32black,
	OBJ_FINALEGGTexName_d64blueeye,
	OBJ_FINALEGGTexName_d64hadabase,
	OBJ_FINALEGGTexName_d64redbase,
	OBJ_FINALEGGTexName_d64redeye,
	OBJ_FINALEGGTexName_d64redmune,
	OBJ_FINALEGGTexName_d64whitebase,
	OBJ_FINALEGGTexName_d64yebase,
	OBJ_FINALEGGTexName_d64yeeye,
	OBJ_FINALEGGTexName_d64yetale,
	OBJ_FINALEGGTexName_d8black,
	OBJ_FINALEGGTexName_d8hada,
	OBJ_FINALEGGTexName_d8white,
	OBJ_FINALEGGTexName_fq64gumblue02,
	OBJ_FINALEGGTexName_d64bluebase,
	OBJ_FINALEGGTexName_tm128uega,
	OBJ_FINALEGGTexName_tm32red1,
	OBJ_FINALEGGTexName_tm32yelvv,
	OBJ_FINALEGGTexName_tm32yelz,
	OBJ_FINALEGGTexName_tm64bk1,
	OBJ_FINALEGGTexName_tm64bl3,
	OBJ_FINALEGGTexName_tm64grip,
	OBJ_FINALEGGTexName_d32mileshoose1,
	OBJ_FINALEGGTexName_d32mileshoose2,
	OBJ_FINALEGGTexName_d32nacshoose1,
	OBJ_FINALEGGTexName_d32nacshoose2,
	OBJ_FINALEGGTexName_d32sonicshoose,
	OBJ_FINALEGGTexName_d32sonicshoose2,
	OBJ_FINALEGGTexName_d128side2f,
	OBJ_FINALEGGTexName_tm128sabis,
	OBJ_FINALEGGTexName_tm16eye2,
	OBJ_FINALEGGTexName_tm16reds,
	OBJ_FINALEGGTexName_tm16shada,
	OBJ_FINALEGGTexName_d128side_moto,
	OBJ_FINALEGGTexName_tm64bl,
	OBJ_FINALEGGTexName_tm64hoho,
	OBJ_FINALEGGTexName_tm64shara,
	OBJ_FINALEGGTexName_d64accent1f,
	OBJ_FINALEGGTexName_d64tunagi2f,
	OBJ_FINALEGGTexName_fq128pipesabi01,
	OBJ_FINALEGGTexName_fq128sabitile02,
	OBJ_FINALEGGTexName_fq64kabelight03,
	OBJ_FINALEGGTexName_fq64wall17,
	OBJ_FINALEGGTexName_tm126garab,
	OBJ_FINALEGGTexName_tm128cont,
	OBJ_FINALEGGTexName_tm128gata,
	OBJ_FINALEGGTexName_tm128gripaa,
	OBJ_FINALEGGTexName_tm128sbox,
	OBJ_FINALEGGTexName_tm32blu,
	OBJ_FINALEGGTexName_tm32deki,
	OBJ_FINALEGGTexName_tm64bkgg,
	OBJ_FINALEGGTexName_d8red,
	OBJ_FINALEGGTexName_tm64blin,
	OBJ_FINALEGGTexName_tm64egggren,
	OBJ_FINALEGGTexName_ai32futa01,
	OBJ_FINALEGGTexName_fq64kabelight02,
	OBJ_FINALEGGTexName_tm128kos,
	OBJ_FINALEGGTexName_ai128kabe07,
	OBJ_FINALEGGTexName_ai128box08,
	OBJ_FINALEGGTexName_fq128compane01,
	OBJ_FINALEGGTexName_fq128rack,
	OBJ_FINALEGGTexName_fq128wall22,
	OBJ_FINALEGGTexName_fq32wanigum01,
	OBJ_FINALEGGTexName_ai128box06,
	OBJ_FINALEGGTexName_fq64wall13,
	OBJ_FINALEGGTexName_fq64wall16,
	OBJ_FINALEGGTexName_fq64yb,
	OBJ_FINALEGGTexName_fq64zakobody_gly,
	OBJ_FINALEGGTexName_fq128pipesabi02,
	OBJ_FINALEGGTexName_ai128box09,
	OBJ_FINALEGGTexName_ai128box10,
	OBJ_FINALEGGTexName_ai64aamu10,
	OBJ_FINALEGGTexName_fq64alpheye,
	OBJ_FINALEGGTexName_ai128box05,
	OBJ_FINALEGGTexName_ai128kabe06,
	OBJ_FINALEGGTexName_ai32box,
	OBJ_FINALEGGTexName_ai32hou05,
	OBJ_FINALEGGTexName_ai64aamu05,
	OBJ_FINALEGGTexName_ai64kabe,
	OBJ_FINALEGGTexName_ai64kabe04,
	OBJ_FINALEGGTexName_ai64kabe08,
	OBJ_FINALEGGTexName_ai64mizo,
	OBJ_FINALEGGTexName_d128_lv1_1gl,
	OBJ_FINALEGGTexName_d64belt1a,
	OBJ_FINALEGGTexName_d128_lv1_2a,
	OBJ_FINALEGGTexName_d128side11f,
	OBJ_FINALEGGTexName_d128side12f,
	OBJ_FINALEGGTexName_d128side13f,
	OBJ_FINALEGGTexName_d128side14f,
	OBJ_FINALEGGTexName_d128side16f,
	OBJ_FINALEGGTexName_d64belcon1a,
	OBJ_FINALEGGTexName_d64hqri1f,
	OBJ_FINALEGGTexName_d64kouji2a,
	OBJ_FINALEGGTexName_d64pipe1a,
	OBJ_FINALEGGTexName_d64side8fe,
	OBJ_FINALEGGTexName_d64yuka1f,
	OBJ_FINALEGGTexName_d128belcon3a,
	OBJ_FINALEGGTexName_d64belcon2a,
	OBJ_FINALEGGTexName_d64pipe2b,
	OBJ_FINALEGGTexName_tm128contf,
	OBJ_FINALEGGTexName_d128dramcan1a,
	OBJ_FINALEGGTexName_d128dramcan2a,
	OBJ_FINALEGGTexName_d32amife1alpha,
	OBJ_FINALEGGTexName_d128shatter3f,
	OBJ_FINALEGGTexName_d128shatter2f,
	OBJ_FINALEGGTexName_ai64aamu06,
	OBJ_FINALEGGTexName_ai64aamu08,
	OBJ_FINALEGGTexName_ai32kou02,
	OBJ_FINALEGGTexName_ai32hou03,
	OBJ_FINALEGGTexName_ai64door08,
	OBJ_FINALEGGTexName_ai64door02,
	OBJ_FINALEGGTexName_ai64door03,
	OBJ_FINALEGGTexName_ai64door04,
	OBJ_FINALEGGTexName_ai64door05,
	OBJ_FINALEGGTexName_ai64door07,
	OBJ_FINALEGGTexName_ai128box02,
	OBJ_FINALEGGTexName_d8pinkwhite,
	OBJ_FINALEGGTexName_d8pink_alpha,
	OBJ_FINALEGGTexName_d8yellow,
	OBJ_FINALEGGTexName_fr32lightbl01,
	OBJ_FINALEGGTexName_d32houdenhikari,
	OBJ_FINALEGGTexName_tm64xxx,
	OBJ_FINALEGGTexName_tm64gripy,
	OBJ_FINALEGGTexName_fq128lv2fan2,
	OBJ_FINALEGGTexName_fq128phead,
	OBJ_FINALEGGTexName_fr64lightbl01,
	OBJ_FINALEGGTexName_ai64aamu07,
	OBJ_FINALEGGTexName_ai64box02,
	OBJ_FINALEGGTexName_ai64box,
	OBJ_FINALEGGTexName_d16arm3f,
	OBJ_FINALEGGTexName_d16arm2f,
	OBJ_FINALEGGTexName_fq64yukaami05,
	OBJ_FINALEGGTexName_tm64bla,
	OBJ_FINALEGGTexName_tm16beam1,
	OBJ_FINALEGGTexName_tm64ligyr,
	OBJ_FINALEGGTexName_fq32rackneji
};

NJS_MATERIAL matlist_001AEB58[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm16beam2, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE | 0x40 }
};

Sint16 poly_001AEB6C[] = {
	4, 8, 15, 0, 7,
	4, 9, 8, 1, 0,
	4, 10, 9, 2, 1,
	4, 11, 10, 3, 2,
	4, 12, 11, 4, 3,
	4, 13, 12, 5, 4,
	4, 14, 13, 6, 5,
	4, 15, 14, 7, 6
};

NJS_TEX uv_001AEBBC[] = {
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 }
};

NJS_MESHSET_SADX meshlist_001AEC3C[] = {
	{ NJD_MESHSET_TRIMESH | 0, 8, poly_001AEB6C, NULL, NULL, NULL, uv_001AEBBC, NULL }
};

NJS_VECTOR vertex_001AEC54[] = {
	{ -3.59639f, -0.8789639f, 8.276591f },
	{ -2.553436f, -3.396901f, 8.276591f },
	{ -0.035562f, -4.439849f, 8.276591f },
	{ 2.482371f, -3.396901f, 8.276587f },
	{ 3.525323f, -0.879028f, 8.276591f },
	{ 2.482371f, 1.638908f, 8.276587f },
	{ -0.035499f, 2.681859f, 8.276591f },
	{ -2.553437f, 1.638908f, 8.276591f },
	{ -14.56535f, -0.859799f, 187.2206f },
	{ -10.3414f, -11.05744f, 187.2206f },
	{ -0.144027f, -15.28137f, 187.2206f },
	{ 10.0536f, -11.05744f, 187.2205f },
	{ 14.27755f, -0.860064f, 187.2206f },
	{ 10.0536f, 9.337571f, 187.2205f },
	{ -0.14377f, 13.56153f, 187.2206f },
	{ -10.3414f, 9.337571f, 187.2206f }
};

NJS_VECTOR normal_001AED14[] = {
	{ -0.998127f, -0.00022f, -0.061183f },
	{ -0.705707f, -0.705879f, -0.060932f },
	{ 0.000146f, -0.99817f, -0.060475f },
	{ 0.705888f, -0.705771f, -0.06008f },
	{ 0.9982f, -0.00031f, -0.059979f },
	{ 0.705915f, 0.705731f, -0.06023f },
	{ 0.000155f, 0.998157f, -0.060687f },
	{ -0.705721f, 0.705851f, -0.061082f },
	{ -0.998127f, 0.00003f, -0.061183f },
	{ -0.70588f, -0.7057059f, -0.060932f },
	{ -0.00015f, -0.99817f, -0.060475f },
	{ 0.705766f, -0.705892f, -0.06008f },
	{ 0.9982f, 0.000021f, -0.059979f },
	{ 0.7057419f, 0.7059039f, -0.06023f },
	{ -0.000141f, 0.998157f, -0.060687f },
	{ -0.705843f, 0.70573f, -0.061082f }
};

NJS_MODEL_SADX attach_001AEDD4 = { vertex_001AEC54, normal_001AED14, LengthOfArray(vertex_001AEC54), meshlist_001AEC3C, matlist_001AEB58, LengthOfArray(meshlist_001AEC3C), LengthOfArray(matlist_001AEB58),{ -0.143901f, -0.859919f, 97.7486f }, 90.62682f, NULL };

NJS_OBJECT object_001AEDFC = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_001AEDD4, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Laser
NJS_MATERIAL matlist_015D8944[] = {
	{ { 0xFFFFE6E7 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_d8pinkwhite, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE },
	{ { 0xFFFF0088 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_d8pink_alpha, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE }
};

Sint16 poly_015D896C[] = {
	0x8000u | 8, 15, 3, 6, 11, 13, 12, 14, 2,
	4, 6, 15, 2, 12
};

Sint16 poly_015D8988[] = {
	4, 0, 4, 5, 9,
	8, 4, 7, 9, 10, 8, 0, 1, 5
};

NJS_TEX uv_015D89A4[] = {
	{ 109, 31 },
	{ 0, 142 },
	{ 0, 142 },
	{ 109, 254 },
	{ 109, 254 },
	{ 223, 142 },
	{ 223, 142 },
	{ 109, 31 },
	{ 0, 142 },
	{ 109, 31 },
	{ 109, 31 },
	{ 223, 142 }
};

NJS_TEX uv_015D89D4[] = {
	{ 175, 142 },
	{ 109, 210 },
	{ 109, 210 },
	{ 47, 142 },
	{ 109, 210 },
	{ 47, 142 },
	{ 47, 142 },
	{ 109, 76 },
	{ 109, 76 },
	{ 175, 142 },
	{ 175, 142 },
	{ 109, 210 }
};

NJS_MESHSET_SADX meshlist_015D8A04[] = {
	{ NJD_MESHSET_TRIMESH | 0, 2, poly_015D8988, NULL, NULL, NULL, uv_015D89D4, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 2, poly_015D896C, NULL, NULL, NULL, uv_015D89A4, NULL }
};

NJS_VECTOR vertex_015D8A40[] = {
	{ 0.699638f, 0, -0.25f },
	{ 0.699638f, 0, -5 },
	{ 0, 1.275362f, -5 },
	{ -1.165217f, 0, 0 },
	{ 0, -0.77913f, -0.25f },
	{ 0, -0.77913f, -5 },
	{ -1.165217f, 0, -5 },
	{ -0.665217f, 0, -0.25f },
	{ 0, 0.765362f, -5 },
	{ -0.665217f, 0, -5 },
	{ 0, 0.765362f, -0.25f },
	{ 0, -1.28913f, 0 },
	{ 1.199638f, 0, 0 },
	{ 0, -1.28913f, -5 },
	{ 1.199638f, 0, -5 },
	{ 0, 1.275362f, 0 }
};

NJS_VECTOR normal_015D8B00[] = {
	{ 0.99999f, 0.004436f, 0 },
	{ 0.99999f, 0.004436f, 0 },
	{ -0.007257f, 0.999974f, 0 },
	{ -0.999996f, 0.002672f, 0 },
	{ -0.0125f, -0.999922f, 0 },
	{ -0.0125f, -0.999922f, 0 },
	{ -0.999996f, 0.002672f, 0 },
	{ -0.99999f, 0.004408f, 0 },
	{ -0.012528f, 0.999922f, 0 },
	{ -0.99999f, 0.004408f, 0 },
	{ -0.012528f, 0.999922f, 0 },
	{ -0.00725f, -0.999974f, 0 },
	{ 0.999996f, 0.002678f, 0 },
	{ -0.00725f, -0.999974f, 0 },
	{ 0.999996f, 0.002678f, 0 },
	{ -0.007257f, 0.999974f, 0 }
};

NJS_MODEL_SADX attach_015D8BC0 = { vertex_015D8A40, normal_015D8B00, LengthOfArray(vertex_015D8A40), meshlist_015D8A04, matlist_015D8944, LengthOfArray(meshlist_015D8A04), LengthOfArray(matlist_015D8944),{ 0.01721f, -0.006884f, -2.5f }, 2.809654f, NULL };

NJS_OBJECT object_015D8BEC = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_015D8BC0, 0, 6.88297f, 4.5f, 0, 0, 0, 1, 1, 1, NULL, NULL };

NJS_OBJECT object_015D8C20 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_HIDE, NULL, 0, 0, 0, 0, 0, 0, 1, 1, 1, &object_015D8BEC, NULL };

//O Stand Light
NJS_MATERIAL matlist_01828018[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 151, NJD_D_200 | NJD_FILTER_TRILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 76, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 32, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 43, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 18, NJD_D_200 | NJD_FILTER_TRILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE }
};

Sint16 poly_0182807C[] = {
	0x8000u | 6, 2, 17, 5, 14, 8, 11
};

Sint16 poly_0182808C[] = {
	4, 4, 1, 3, 0,
	4, 7, 4, 6, 3,
	4, 1, 16, 0, 15,
	4, 16, 13, 15, 12,
	4, 10, 7, 9, 6,
	4, 13, 10, 12, 9
};

Sint16 poly_018280C8[] = {
	4, 5, 2, 4, 1,
	4, 2, 17, 1, 16,
	4, 8, 5, 7, 4,
	4, 11, 8, 10, 7,
	4, 17, 14, 16, 13,
	4, 14, 11, 13, 10
};

Sint16 poly_01828104[] = {
	0x8000u | 6, 12, 15, 9, 0, 6, 3
};

Sint16 poly_01828114[] = {
	4, 20, 21, 19, 18,
	4, 24, 25, 23, 22
};

NJS_TEX uv_01828128[] = {
	{ 223, 31 },
	{ 0, 31 },
	{ 223, 143 },
	{ 0, 143 },
	{ 223, 255 },
	{ 0, 255 }
};

NJS_TEX uv_01828140[] = {
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 }
};

NJS_TEX uv_018281A0[] = {
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 }
};

NJS_TEX uv_01828200[] = {
	{ 0, 255 },
	{ 223, 255 },
	{ 0, 143 },
	{ 223, 143 },
	{ 0, 31 },
	{ 223, 31 }
};

NJS_TEX uv_01828218[] = {
	{ 7, 23 },
	{ 231, 23 },
	{ 7, 247 },
	{ 231, 247 },
	{ 7, 23 },
	{ 231, 23 },
	{ 7, 247 },
	{ 231, 247 }
};

NJS_MESHSET_SADX meshlist_01828238[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_0182807C, NULL, NULL, NULL, uv_01828128, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 6, poly_0182808C, NULL, NULL, NULL, uv_01828140, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 6, poly_018280C8, NULL, NULL, NULL, uv_018281A0, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 1, poly_01828104, NULL, NULL, NULL, uv_01828200, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_01828114, NULL, NULL, NULL, uv_01828218, NULL }
};

NJS_VECTOR vertex_018282C8[] = {
	{ 0.492801f, -0.075478f, -0.798372f },
	{ 0.492801f, -0.075478f, 1.232754f },
	{ 0.211905f, -0.075478f, 1.023453f },
	{ 0.2464f, 0.3513f, -0.798372f },
	{ 0.2464f, 0.3513f, 1.232754f },
	{ 0.105952f, 0.108037f, 1.023453f },
	{ -0.2464f, 0.3513f, -0.798372f },
	{ -0.2464f, 0.3513f, 1.232754f },
	{ -0.105952f, 0.108037f, 1.023453f },
	{ -0.492801f, -0.075478f, -0.798372f },
	{ -0.492801f, -0.075478f, 1.232754f },
	{ -0.211905f, -0.075478f, 1.023453f },
	{ -0.2464f, -0.502255f, -0.798372f },
	{ -0.2464f, -0.502255f, 1.232754f },
	{ -0.105952f, -0.258992f, 1.023453f },
	{ 0.2464f, -0.502255f, -0.798372f },
	{ 0.2464f, -0.502255f, 1.232754f },
	{ 0.105952f, -0.258992f, 1.023453f },
	{ -0.361256f, -0.099413f, 1.204595f },//
	{ -3.893497f, -0.099413f, 28.10469f },
	{ 3.223505f, -0.099413f, 28.10469f },
	{ 0.322192f, -0.099413f, 1.204595f },//
	/*{ 0,0,0 },
	{ 0,0,0 },
	{ 0,0,0 },
	{ 0,0,0 },*/
	{ 0.015073f, 0.276916f, 1.204595f },
	{ 0.015073f, 3.809155f, 28.10469f },
	{ 0.015073f, -3.888825f, 28.10469f },
	{ 0.015073f, -0.424051f, 1.204595f }
};

NJS_VECTOR normal_01828400[] = {
	{ 0.792406f, 0, -0.609994f },
	{ 0.626711f, 0, 0.779252f },
	{ -0.402126f, 0, 0.915584f },
	{ 0.396203f, 0.686244f, -0.609994f },
	{ 0.313356f, 0.542748f, 0.779252f },
	{ -0.201063f, -0.348251f, 0.915584f },
	{ -0.396203f, 0.686244f, -0.609994f },
	{ -0.313356f, 0.542748f, 0.779252f },
	{ 0.201063f, -0.348251f, 0.915584f },
	{ -0.792406f, 0, -0.609994f },
	{ -0.626711f, 0, 0.779252f },
	{ 0.402126f, 0, 0.915584f },
	{ -0.396203f, -0.686244f, -0.609994f },
	{ -0.313355f, -0.542748f, 0.779252f },
	{ 0.201063f, 0.348251f, 0.915584f },
	{ 0.396203f, -0.686244f, -0.609994f },
	{ 0.313356f, -0.542748f, 0.779252f },
	{ -0.201063f, 0.348251f, 0.915584f },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 1, 0, 0 },
	{ 1, 0, 0 },
	{ 1, 0, 0 },
	{ 1, 0, 0 }
};

NJS_MODEL_SADX attach_01828538 = { vertex_018282C8, normal_01828400, LengthOfArray(vertex_018282C8), meshlist_01828238, matlist_01828018, LengthOfArray(meshlist_01828238), LengthOfArray(matlist_01828018),{ -0.334996f, -0.039835f, 13.65316f }, 15.07127f, NULL };

NJS_OBJECT object_01828564 = { NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_01828538, 0, 11.11258f, -0.867072f, 0xFFFFFCBE, 0, 0, 1, 1, 1, NULL, NULL };


NJS_MATERIAL matlist_01828598[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 12, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_FLAG_USE_ENV | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 32, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 48, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 83, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 20, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFF4D4948 },{ 0xFFFFFFFF }, 11, 14, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_01828610[] = {
	0x8000u | 5, 4, 2, 0, 12, 10,
	0x8000u | 5, 10, 8, 0, 6, 4,
	14, 7, 6, 5, 4, 3, 2, 1, 12, 11, 10, 9, 8, 7, 6
};

Sint16 poly_01828648[] = {
	4, 24, 28, 23, 27,
	4, 26, 24, 25, 23,
	4, 28, 26, 27, 25
};

Sint16 poly_01828668[] = {
	0x8000u | 5, 14, 22, 16, 20, 18,
	0x8000u | 5, 17, 19, 15, 21, 13
};

Sint16 poly_01828680[] = {
	4, 22, 20, 21, 19,
	4, 20, 18, 19, 17,
	4, 16, 14, 15, 13,
	4, 18, 16, 17, 15,
	4, 14, 22, 13, 21
};

Sint16 poly_018286B4[] = {
	0x8000u | 8, 31, 35, 32, 36, 29, 33, 30, 34
};

Sint16 poly_018286C8[] = {
	4, 35, 36, 34, 33,
	4, 30, 29, 31, 32
};

NJS_TEX uv_018286E0[] = {
	{ 163, 210 },
	{ 199, 149 },
	{ 126, 149 },
	{ 163, 88 },
	{ 89, 88 },
	{ 89, 88 },
	{ 53, 149 },
	{ 126, 149 },
	{ 89, 210 },
	{ 163, 210 },
	{ 0, 149 },
	{ 89, 210 },
	{ 63, 254 },
	{ 163, 210 },
	{ 189, 254 },
	{ 199, 149 },
	{ 253, 149 },
	{ 163, 88 },
	{ 189, 43 },
	{ 89, 88 },
	{ 63, 43 },
	{ 53, 149 },
	{ 0, 149 },
	{ 89, 210 }
};

NJS_TEX uv_01828740[] = {
	{ 0, 255 },
	{ 0, 15 },
	{ 5100, 255 },
	{ 5100, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 5100, 255 },
	{ 5100, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 5100, 255 },
	{ 5100, 15 }
};

NJS_TEX uv_01828770[] = {
	{ 0, 222 },
	{ 249, 221 },
	{ 3, 53 },
	{ 253, 54 },
	{ 133, -1 },
	{ 133, 12 },
	{ 245, 56 },
	{ 8, 56 },
	{ 244, 220 },
	{ 7, 218 }
};

NJS_TEX uv_01828798[] = {
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 }
};

NJS_TEX uv_018287E8[] = {
	{ 247, -1275 },
	{ 0, -1275 },
	{ 247, -688 },
	{ 0, -688 },
	{ 247, -439 },
	{ 0, -439 },
	{ 247, 255 },
	{ 0, 255 }
};

NJS_TEX uv_01828808[] = {
	{ 0, 254 },
	{ 0, 28 },
	{ 253, 254 },
	{ 128, 1 },
	{ 253, 254 },
	{ 128, 1 },
	{ 0, 254 },
	{ 0, 28 }
};

NJS_MESHSET_SADX meshlist_01828828[] = {
	{ NJD_MESHSET_TRIMESH | 0, 3, poly_01828610, NULL, NULL, NULL, uv_018286E0, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 3, poly_01828648, NULL, NULL, NULL, uv_01828740, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_01828668, NULL, NULL, NULL, uv_01828770, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 5, poly_01828680, NULL, NULL, NULL, uv_01828798, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 1, poly_018286B4, NULL, NULL, NULL, uv_018287E8, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 2, poly_018286C8, NULL, NULL, NULL, uv_01828808, NULL }
};

NJS_VECTOR vertex_018288D0[] = {
	{ 0, 0.828626f, -0.263483f },
	{ 1.486466f, 0.01394f, -0.263483f },
	{ 0.858212f, 0.610332f, -0.263483f },
	{ 0.743233f, 0.01394f, -1.550801f },
	{ 0.429106f, 0.610332f, -1.006716f },
	{ -0.743233f, 0.01394f, -1.5508f },
	{ -0.429106f, 0.610332f, -1.006716f },
	{ -1.486466f, 0.01394f, -0.263483f },
	{ -0.858212f, 0.610332f, -0.263483f },
	{ -0.743233f, 0.01394f, 1.023834f },
	{ -0.429106f, 0.610332f, 0.47975f },
	{ 0.743233f, 0.01394f, 1.023834f },
	{ 0.429106f, 0.610332f, 0.47975f },
	{ -0.836994f, 9.123271f, -1.106837f },
	{ -0.891397f, 9.769961f, -1.154505f },
	{ -0.83034f, 9.123271f, 0.838524f },
	{ -0.868009f, 9.769961f, 0.869377f },
	{ 0.024349f, 9.123271f, 1.366645f },
	{ 0.028606f, 9.769961f, 1.528495f },
	{ 0.793967f, 9.123271f, 0.833752f },
	{ 0.846949f, 9.769961f, 0.856082f },
	{ 0.785781f, 9.123271f, -1.131165f },
	{ 0.821567f, 9.769961f, -1.15374f },
	{ 0.007017f, 0.595133f, 0.048774f },
	{ 0.007017f, 9.142028f, 0.048774f },
	{ 0.277883f, 0.595133f, -0.44469f },
	{ 0.277883f, 9.151853f, -0.44469f },
	{ -0.284902f, 0.595133f, -0.432535f },
	{ -0.284902f, 9.151853f, -0.432535f },
	{ -0.7f, 11.31025f, -0.358304f },
	{ -0.7f, 9.773953f, 0.185589f },
	{ -0.7f, 9.773953f, -0.918194f },
	{ -0.7f, 11.15022f, -0.918194f },
	{ 0.7f, 11.31025f, -0.358304f },
	{ 0.7f, 9.773953f, 0.185589f },
	{ 0.7f, 9.773953f, -0.918194f },
	{ 0.7f, 11.15022f, -0.918194f }
};

NJS_VECTOR normal_01828A90[] = {
	{ 0, 1, 0 },
	{ 0.688477f, 0.725259f, 0 },
	{ 0.5418f, 0.840507f, 0 },
	{ 0.344238f, 0.725258f, -0.596238f },
	{ 0.2709f, 0.840507f, -0.469213f },
	{ -0.344238f, 0.725258f, -0.596238f },
	{ -0.2709f, 0.840507f, -0.469213f },
	{ -0.688477f, 0.725258f, 0 },
	{ -0.5418f, 0.840507f, 0 },
	{ -0.344238f, 0.725258f, 0.596238f },
	{ -0.2709f, 0.840507f, 0.469213f },
	{ 0.344238f, 0.725258f, 0.596238f },
	{ 0.2709f, 0.840507f, 0.469213f },
	{ -0.561948f, -0.612224f, -0.556234f },
	{ -0.600251f, 0.54306f, -0.587183f },
	{ -0.657467f, -0.670106f, 0.344521f },
	{ -0.730864f, 0.559411f, 0.39102f },
	{ 0.024531f, -0.667413f, 0.744284f },
	{ 0.027893f, 0.530185f, 0.847423f },
	{ 0.690185f, -0.638575f, 0.340392f },
	{ 0.71938f, 0.598724f, 0.352166f },
	{ 0.551079f, -0.612806f, -0.566375f },
	{ 0.594559f, 0.540965f, -0.594858f },
	{ 0.021593f, 0, 0.999767f },
	{ 0.021593f, 0, 0.999767f },
	{ 0.855027f, 0, -0.518584f },
	{ 0.849969f, 0, -0.526832f },
	{ -0.87662f, 0, -0.481183f },
	{ -0.871924f, 0, -0.489642f },
	{ -0.580673f, 0.723608f, 0.373109f },
	{ -0.616687f, 0.262717f, 0.742077f },
	{ -0.707107f, 0, -0.707107f },
	{ -0.59342f, 0.48467f, -0.64261f },
	{ 0.580673f, 0.723608f, 0.373109f },
	{ 0.616687f, 0.262717f, 0.742077f },
	{ 0.707107f, 0, -0.707107f },
	{ 0.59342f, 0.48467f, -0.64261f }
};

NJS_MODEL_SADX attach_01828C4C = { vertex_018288D0, normal_01828A90, LengthOfArray(vertex_018288D0), meshlist_01828828, matlist_01828598, LengthOfArray(meshlist_01828828), LengthOfArray(matlist_01828598),{ 0, 5.662093f, -0.011153f }, 5.854242f, NULL };

NJS_OBJECT object_01828C78 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL, &attach_01828C4C, 0, 0, 0, 0, 0, 0, 1, 1, 1, &object_01828564, NULL };