/* NINJA Basic (with Sonic Adventure DX additions) model
*
* Generated by SAMDL
*
*/

enum OBJ_FINALEGGTexName
{
	OBJ_FINALEGGTexName_d64arm4f,
	OBJ_FINALEGGTexName_d64metal1f,
	OBJ_FINALEGGTexName_d64metal2f,
	OBJ_FINALEGGTexName_d64tunagi1f,
	OBJ_FINALEGGTexName_tm128dak,
	OBJ_FINALEGGTexName_tm16sya,
	OBJ_FINALEGGTexName_tm16cam,
	OBJ_FINALEGGTexName_tm32gars,
	OBJ_FINALEGGTexName_tm64ginp,
	OBJ_FINALEGGTexName_tm64green,
	OBJ_FINALEGGTexName_tm64grnx,
	OBJ_FINALEGGTexName_tm64limo,
	OBJ_FINALEGGTexName_tm128tec,
	OBJ_FINALEGGTexName_fq64mtl_base01,
	OBJ_FINALEGGTexName_tm128gateja,
	OBJ_FINALEGGTexName_tm128keiki2,
	OBJ_FINALEGGTexName_d16jet1alfa,
	OBJ_FINALEGGTexName_tym64bkl,
	OBJ_FINALEGGTexName_tm16beam3,
	OBJ_FINALEGGTexName_d64_lv1_1c,
	OBJ_FINALEGGTexName_tm32bk1,
	OBJ_FINALEGGTexName_tm32gars2,
	OBJ_FINALEGGTexName_tm16yel,
	OBJ_FINALEGGTexName_tm64objgr1,
	OBJ_FINALEGGTexName_tm64objgr2,
	OBJ_FINALEGGTexName_tm128keiki,
	OBJ_FINALEGGTexName_d64tunagi5f,
	OBJ_FINALEGGTexName_fq128wall21,
	OBJ_FINALEGGTexName_fq64sabi02,
	OBJ_FINALEGGTexName_d128_lv1_1b,
	OBJ_FINALEGGTexName_tm128saba,
	OBJ_FINALEGGTexName_tm16beam2,
	OBJ_FINALEGGTexName_tm16bkbk,
	OBJ_FINALEGGTexName_tm32black,
	OBJ_FINALEGGTexName_d64blueeye,
	OBJ_FINALEGGTexName_d64hadabase,
	OBJ_FINALEGGTexName_d64redbase,
	OBJ_FINALEGGTexName_d64redeye,
	OBJ_FINALEGGTexName_d64redmune,
	OBJ_FINALEGGTexName_d64whitebase,
	OBJ_FINALEGGTexName_d64yebase,
	OBJ_FINALEGGTexName_d64yeeye,
	OBJ_FINALEGGTexName_d64yetale,
	OBJ_FINALEGGTexName_d8black,
	OBJ_FINALEGGTexName_d8hada,
	OBJ_FINALEGGTexName_d8white,
	OBJ_FINALEGGTexName_fq64gumblue02,
	OBJ_FINALEGGTexName_d64bluebase,
	OBJ_FINALEGGTexName_tm128uega,
	OBJ_FINALEGGTexName_tm32red1,
	OBJ_FINALEGGTexName_tm32yelvv,
	OBJ_FINALEGGTexName_tm32yelz,
	OBJ_FINALEGGTexName_tm64bk1,
	OBJ_FINALEGGTexName_tm64bl3,
	OBJ_FINALEGGTexName_tm64grip,
	OBJ_FINALEGGTexName_d32mileshoose1,
	OBJ_FINALEGGTexName_d32mileshoose2,
	OBJ_FINALEGGTexName_d32nacshoose1,
	OBJ_FINALEGGTexName_d32nacshoose2,
	OBJ_FINALEGGTexName_d32sonicshoose,
	OBJ_FINALEGGTexName_d32sonicshoose2,
	OBJ_FINALEGGTexName_d128side2f,
	OBJ_FINALEGGTexName_tm128sabis,
	OBJ_FINALEGGTexName_tm16eye2,
	OBJ_FINALEGGTexName_tm16reds,
	OBJ_FINALEGGTexName_tm16shada,
	OBJ_FINALEGGTexName_d128side_moto,
	OBJ_FINALEGGTexName_tm64bl,
	OBJ_FINALEGGTexName_tm64hoho,
	OBJ_FINALEGGTexName_tm64shara,
	OBJ_FINALEGGTexName_d64accent1f,
	OBJ_FINALEGGTexName_d64tunagi2f,
	OBJ_FINALEGGTexName_fq128pipesabi01,
	OBJ_FINALEGGTexName_fq128sabitile02,
	OBJ_FINALEGGTexName_fq64kabelight03,
	OBJ_FINALEGGTexName_fq64wall17,
	OBJ_FINALEGGTexName_tm126garab,
	OBJ_FINALEGGTexName_tm128cont,
	OBJ_FINALEGGTexName_tm128gata,
	OBJ_FINALEGGTexName_tm128gripaa,
	OBJ_FINALEGGTexName_tm128sbox,
	OBJ_FINALEGGTexName_tm32blu,
	OBJ_FINALEGGTexName_tm32deki,
	OBJ_FINALEGGTexName_tm64bkgg,
	OBJ_FINALEGGTexName_d8red,
	OBJ_FINALEGGTexName_tm64blin,
	OBJ_FINALEGGTexName_tm64egggren,
	OBJ_FINALEGGTexName_ai32futa01,
	OBJ_FINALEGGTexName_fq64kabelight02,
	OBJ_FINALEGGTexName_tm128kos,
	OBJ_FINALEGGTexName_ai128kabe07,
	OBJ_FINALEGGTexName_ai128box08,
	OBJ_FINALEGGTexName_fq128compane01,
	OBJ_FINALEGGTexName_fq128rack,
	OBJ_FINALEGGTexName_fq128wall22,
	OBJ_FINALEGGTexName_fq32wanigum01,
	OBJ_FINALEGGTexName_ai128box06,
	OBJ_FINALEGGTexName_fq64wall13,
	OBJ_FINALEGGTexName_fq64wall16,
	OBJ_FINALEGGTexName_fq64yb,
	OBJ_FINALEGGTexName_fq64zakobody_gly,
	OBJ_FINALEGGTexName_fq128pipesabi02,
	OBJ_FINALEGGTexName_ai128box09,
	OBJ_FINALEGGTexName_ai128box10,
	OBJ_FINALEGGTexName_ai64aamu10,
	OBJ_FINALEGGTexName_fq64alpheye,
	OBJ_FINALEGGTexName_ai128box05,
	OBJ_FINALEGGTexName_ai128kabe06,
	OBJ_FINALEGGTexName_ai32box,
	OBJ_FINALEGGTexName_ai32hou05,
	OBJ_FINALEGGTexName_ai64aamu05,
	OBJ_FINALEGGTexName_ai64kabe,
	OBJ_FINALEGGTexName_ai64kabe04,
	OBJ_FINALEGGTexName_ai64kabe08,
	OBJ_FINALEGGTexName_ai64mizo,
	OBJ_FINALEGGTexName_d128_lv1_1gl,
	OBJ_FINALEGGTexName_d64belt1a,
	OBJ_FINALEGGTexName_d128_lv1_2a,
	OBJ_FINALEGGTexName_d128side11f,
	OBJ_FINALEGGTexName_d128side12f,
	OBJ_FINALEGGTexName_d128side13f,
	OBJ_FINALEGGTexName_d128side14f,
	OBJ_FINALEGGTexName_d128side16f,
	OBJ_FINALEGGTexName_d64belcon1a,
	OBJ_FINALEGGTexName_d64hqri1f,
	OBJ_FINALEGGTexName_d64kouji2a,
	OBJ_FINALEGGTexName_d64pipe1a,
	OBJ_FINALEGGTexName_d64side8fe,
	OBJ_FINALEGGTexName_d64yuka1f,
	OBJ_FINALEGGTexName_d128belcon3a,
	OBJ_FINALEGGTexName_d64belcon2a,
	OBJ_FINALEGGTexName_d64pipe2b,
	OBJ_FINALEGGTexName_tm128contf,
	OBJ_FINALEGGTexName_d128dramcan1a,
	OBJ_FINALEGGTexName_d128dramcan2a,
	OBJ_FINALEGGTexName_d32amife1alpha,
	OBJ_FINALEGGTexName_d128shatter3f,
	OBJ_FINALEGGTexName_d128shatter2f,
	OBJ_FINALEGGTexName_ai64aamu06,
	OBJ_FINALEGGTexName_ai64aamu08,
	OBJ_FINALEGGTexName_ai32kou02,
	OBJ_FINALEGGTexName_ai32hou03,
	OBJ_FINALEGGTexName_ai64door08,
	OBJ_FINALEGGTexName_ai64door02,
	OBJ_FINALEGGTexName_ai64door03,
	OBJ_FINALEGGTexName_ai64door04,
	OBJ_FINALEGGTexName_ai64door05,
	OBJ_FINALEGGTexName_ai64door07,
	OBJ_FINALEGGTexName_ai128box02,
	OBJ_FINALEGGTexName_d8pinkwhite,
	OBJ_FINALEGGTexName_d8pink_alpha,
	OBJ_FINALEGGTexName_d8yellow,
	OBJ_FINALEGGTexName_fr32lightbl01,
	OBJ_FINALEGGTexName_d32houdenhikari,
	OBJ_FINALEGGTexName_tm64xxx,
	OBJ_FINALEGGTexName_tm64gripy,
	OBJ_FINALEGGTexName_fq128lv2fan2,
	OBJ_FINALEGGTexName_fq128phead,
	OBJ_FINALEGGTexName_fr64lightbl01,
	OBJ_FINALEGGTexName_ai64aamu07,
	OBJ_FINALEGGTexName_ai64box02,
	OBJ_FINALEGGTexName_ai64box,
	OBJ_FINALEGGTexName_d16arm3f,
	OBJ_FINALEGGTexName_d16arm2f,
	OBJ_FINALEGGTexName_fq64yukaami05,
	OBJ_FINALEGGTexName_tm64bla,
	OBJ_FINALEGGTexName_tm16beam1,
	OBJ_FINALEGGTexName_tm64ligyr,
	OBJ_FINALEGGTexName_fq32rackneji
};

NJS_MATERIAL matlist_001AEB58[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm16beam2, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE | 0x40 }
};

Sint16 poly_001AEB6C[] = {
	4, 8, 15, 0, 7,
	4, 9, 8, 1, 0,
	4, 10, 9, 2, 1,
	4, 11, 10, 3, 2,
	4, 12, 11, 4, 3,
	4, 13, 12, 5, 4,
	4, 14, 13, 6, 5,
	4, 15, 14, 7, 6
};

NJS_TEX uv_001AEBBC[] = {
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 },
	{ 7, 247 },
	{ 7, 23 },
	{ 231, 247 },
	{ 231, 23 }
};

NJS_MESHSET_SADX meshlist_001AEC3C[] = {
	{ NJD_MESHSET_TRIMESH | 0, 8, poly_001AEB6C, NULL, NULL, NULL, uv_001AEBBC, NULL }
};

NJS_VECTOR vertex_001AEC54[] = {
	{ -3.59639f, -0.8789639f, 8.276591f },
	{ -2.553436f, -3.396901f, 8.276591f },
	{ -0.035562f, -4.439849f, 8.276591f },
	{ 2.482371f, -3.396901f, 8.276587f },
	{ 3.525323f, -0.879028f, 8.276591f },
	{ 2.482371f, 1.638908f, 8.276587f },
	{ -0.035499f, 2.681859f, 8.276591f },
	{ -2.553437f, 1.638908f, 8.276591f },
	{ -14.56535f, -0.859799f, 187.2206f },
	{ -10.3414f, -11.05744f, 187.2206f },
	{ -0.144027f, -15.28137f, 187.2206f },
	{ 10.0536f, -11.05744f, 187.2205f },
	{ 14.27755f, -0.860064f, 187.2206f },
	{ 10.0536f, 9.337571f, 187.2205f },
	{ -0.14377f, 13.56153f, 187.2206f },
	{ -10.3414f, 9.337571f, 187.2206f }
};

NJS_VECTOR normal_001AED14[] = {
	{ -0.998127f, -0.00022f, -0.061183f },
	{ -0.705707f, -0.705879f, -0.060932f },
	{ 0.000146f, -0.99817f, -0.060475f },
	{ 0.705888f, -0.705771f, -0.06008f },
	{ 0.9982f, -0.00031f, -0.059979f },
	{ 0.705915f, 0.705731f, -0.06023f },
	{ 0.000155f, 0.998157f, -0.060687f },
	{ -0.705721f, 0.705851f, -0.061082f },
	{ -0.998127f, 0.00003f, -0.061183f },
	{ -0.70588f, -0.7057059f, -0.060932f },
	{ -0.00015f, -0.99817f, -0.060475f },
	{ 0.705766f, -0.705892f, -0.06008f },
	{ 0.9982f, 0.000021f, -0.059979f },
	{ 0.7057419f, 0.7059039f, -0.06023f },
	{ -0.000141f, 0.998157f, -0.060687f },
	{ -0.705843f, 0.70573f, -0.061082f }
};

NJS_MODEL_SADX attach_001AEDD4 = { vertex_001AEC54, normal_001AED14, LengthOfArray(vertex_001AEC54), meshlist_001AEC3C, matlist_001AEB58, LengthOfArray(meshlist_001AEC3C), LengthOfArray(matlist_001AEB58),{ -0.143901f, -0.859919f, 97.7486f }, 90.62682f, NULL };

NJS_OBJECT object_001AEDFC = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_001AEDD4, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

//Laser
NJS_MATERIAL matlist_015D8944[] = {
	{ { 0xFFFFE6E7 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_d8pinkwhite, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE },
	{ { 0xFFFF0088 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_d8pink_alpha, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE }
};

Sint16 poly_015D896C[] = {
	0x8000u | 8, 15, 3, 6, 11, 13, 12, 14, 2,
	4, 6, 15, 2, 12
};

Sint16 poly_015D8988[] = {
	4, 0, 4, 5, 9,
	8, 4, 7, 9, 10, 8, 0, 1, 5
};

NJS_TEX uv_015D89A4[] = {
	{ 109, 31 },
	{ 0, 142 },
	{ 0, 142 },
	{ 109, 254 },
	{ 109, 254 },
	{ 223, 142 },
	{ 223, 142 },
	{ 109, 31 },
	{ 0, 142 },
	{ 109, 31 },
	{ 109, 31 },
	{ 223, 142 }
};

NJS_TEX uv_015D89D4[] = {
	{ 175, 142 },
	{ 109, 210 },
	{ 109, 210 },
	{ 47, 142 },
	{ 109, 210 },
	{ 47, 142 },
	{ 47, 142 },
	{ 109, 76 },
	{ 109, 76 },
	{ 175, 142 },
	{ 175, 142 },
	{ 109, 210 }
};

NJS_MESHSET_SADX meshlist_015D8A04[] = {
	{ NJD_MESHSET_TRIMESH | 0, 2, poly_015D8988, NULL, NULL, NULL, uv_015D89D4, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 2, poly_015D896C, NULL, NULL, NULL, uv_015D89A4, NULL }
};

NJS_VECTOR vertex_015D8A40[] = {
	{ 0.699638f, 0, -0.25f },
	{ 0.699638f, 0, -5 },
	{ 0, 1.275362f, -5 },
	{ -1.165217f, 0, 0 },
	{ 0, -0.77913f, -0.25f },
	{ 0, -0.77913f, -5 },
	{ -1.165217f, 0, -5 },
	{ -0.665217f, 0, -0.25f },
	{ 0, 0.765362f, -5 },
	{ -0.665217f, 0, -5 },
	{ 0, 0.765362f, -0.25f },
	{ 0, -1.28913f, 0 },
	{ 1.199638f, 0, 0 },
	{ 0, -1.28913f, -5 },
	{ 1.199638f, 0, -5 },
	{ 0, 1.275362f, 0 }
};

NJS_VECTOR normal_015D8B00[] = {
	{ 0.99999f, 0.004436f, 0 },
	{ 0.99999f, 0.004436f, 0 },
	{ -0.007257f, 0.999974f, 0 },
	{ -0.999996f, 0.002672f, 0 },
	{ -0.0125f, -0.999922f, 0 },
	{ -0.0125f, -0.999922f, 0 },
	{ -0.999996f, 0.002672f, 0 },
	{ -0.99999f, 0.004408f, 0 },
	{ -0.012528f, 0.999922f, 0 },
	{ -0.99999f, 0.004408f, 0 },
	{ -0.012528f, 0.999922f, 0 },
	{ -0.00725f, -0.999974f, 0 },
	{ 0.999996f, 0.002678f, 0 },
	{ -0.00725f, -0.999974f, 0 },
	{ 0.999996f, 0.002678f, 0 },
	{ -0.007257f, 0.999974f, 0 }
};

NJS_MODEL_SADX attach_015D8BC0 = { vertex_015D8A40, normal_015D8B00, LengthOfArray(vertex_015D8A40), meshlist_015D8A04, matlist_015D8944, LengthOfArray(meshlist_015D8A04), LengthOfArray(matlist_015D8944),{ 0.01721f, -0.006884f, -2.5f }, 2.809654f, NULL };

NJS_OBJECT object_015D8BEC = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_015D8BC0, 0, 6.88297f, 4.5f, 0, 0, 0, 1, 1, 1, NULL, NULL };

NJS_OBJECT object_015D8C20 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_HIDE, NULL, 0, 0, 0, 0, 0, 0, 1, 1, 1, &object_015D8BEC, NULL };

//O Stand Light
NJS_MATERIAL matlist_01828018[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 151, NJD_D_200 | NJD_FILTER_TRILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 76, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 32, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 43, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 18, NJD_D_200 | NJD_FILTER_TRILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_ONE }
};

Sint16 poly_0182807C[] = {
	0x8000u | 6, 2, 17, 5, 14, 8, 11
};

Sint16 poly_0182808C[] = {
	4, 4, 1, 3, 0,
	4, 7, 4, 6, 3,
	4, 1, 16, 0, 15,
	4, 16, 13, 15, 12,
	4, 10, 7, 9, 6,
	4, 13, 10, 12, 9
};

Sint16 poly_018280C8[] = {
	4, 5, 2, 4, 1,
	4, 2, 17, 1, 16,
	4, 8, 5, 7, 4,
	4, 11, 8, 10, 7,
	4, 17, 14, 16, 13,
	4, 14, 11, 13, 10
};

Sint16 poly_01828104[] = {
	0x8000u | 6, 12, 15, 9, 0, 6, 3
};

Sint16 poly_01828114[] = {
	4, 20, 21, 19, 18,
	4, 24, 25, 23, 22
};

NJS_TEX uv_01828128[] = {
	{ 223, 31 },
	{ 0, 31 },
	{ 223, 143 },
	{ 0, 143 },
	{ 223, 255 },
	{ 0, 255 }
};

NJS_TEX uv_01828140[] = {
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 },
	{ 105, 87 },
	{ 105, 22 },
	{ 252, 87 },
	{ 252, 22 }
};

NJS_TEX uv_018281A0[] = {
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 239, 255 },
	{ 239, 15 }
};

NJS_TEX uv_01828200[] = {
	{ 0, 255 },
	{ 223, 255 },
	{ 0, 143 },
	{ 223, 143 },
	{ 0, 31 },
	{ 223, 31 }
};

NJS_TEX uv_01828218[] = {
	{ 7, 23 },
	{ 231, 23 },
	{ 7, 247 },
	{ 231, 247 },
	{ 7, 23 },
	{ 231, 23 },
	{ 7, 247 },
	{ 231, 247 }
};

NJS_MESHSET_SADX meshlist_01828238[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_0182807C, NULL, NULL, NULL, uv_01828128, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 6, poly_0182808C, NULL, NULL, NULL, uv_01828140, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 6, poly_018280C8, NULL, NULL, NULL, uv_018281A0, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 1, poly_01828104, NULL, NULL, NULL, uv_01828200, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 2, poly_01828114, NULL, NULL, NULL, uv_01828218, NULL }
};

NJS_VECTOR vertex_018282C8[] = {
	{ 0.492801f, -0.075478f, -0.798372f },
	{ 0.492801f, -0.075478f, 1.232754f },
	{ 0.211905f, -0.075478f, 1.023453f },
	{ 0.2464f, 0.3513f, -0.798372f },
	{ 0.2464f, 0.3513f, 1.232754f },
	{ 0.105952f, 0.108037f, 1.023453f },
	{ -0.2464f, 0.3513f, -0.798372f },
	{ -0.2464f, 0.3513f, 1.232754f },
	{ -0.105952f, 0.108037f, 1.023453f },
	{ -0.492801f, -0.075478f, -0.798372f },
	{ -0.492801f, -0.075478f, 1.232754f },
	{ -0.211905f, -0.075478f, 1.023453f },
	{ -0.2464f, -0.502255f, -0.798372f },
	{ -0.2464f, -0.502255f, 1.232754f },
	{ -0.105952f, -0.258992f, 1.023453f },
	{ 0.2464f, -0.502255f, -0.798372f },
	{ 0.2464f, -0.502255f, 1.232754f },
	{ 0.105952f, -0.258992f, 1.023453f },
	{ -0.361256f, -0.099413f, 1.204595f },//
	{ -3.893497f, -0.099413f, 28.10469f },
	{ 3.223505f, -0.099413f, 28.10469f },
	{ 0.322192f, -0.099413f, 1.204595f },//
	/*{ 0,0,0 },
	{ 0,0,0 },
	{ 0,0,0 },
	{ 0,0,0 },*/
	{ 0.015073f, 0.276916f, 1.204595f },
	{ 0.015073f, 3.809155f, 28.10469f },
	{ 0.015073f, -3.888825f, 28.10469f },
	{ 0.015073f, -0.424051f, 1.204595f }
};

NJS_VECTOR normal_01828400[] = {
	{ 0.792406f, 0, -0.609994f },
	{ 0.626711f, 0, 0.779252f },
	{ -0.402126f, 0, 0.915584f },
	{ 0.396203f, 0.686244f, -0.609994f },
	{ 0.313356f, 0.542748f, 0.779252f },
	{ -0.201063f, -0.348251f, 0.915584f },
	{ -0.396203f, 0.686244f, -0.609994f },
	{ -0.313356f, 0.542748f, 0.779252f },
	{ 0.201063f, -0.348251f, 0.915584f },
	{ -0.792406f, 0, -0.609994f },
	{ -0.626711f, 0, 0.779252f },
	{ 0.402126f, 0, 0.915584f },
	{ -0.396203f, -0.686244f, -0.609994f },
	{ -0.313355f, -0.542748f, 0.779252f },
	{ 0.201063f, 0.348251f, 0.915584f },
	{ 0.396203f, -0.686244f, -0.609994f },
	{ 0.313356f, -0.542748f, 0.779252f },
	{ -0.201063f, 0.348251f, 0.915584f },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 1, 0, 0 },
	{ 1, 0, 0 },
	{ 1, 0, 0 },
	{ 1, 0, 0 }
};

NJS_MODEL_SADX attach_01828538 = { vertex_018282C8, normal_01828400, LengthOfArray(vertex_018282C8), meshlist_01828238, matlist_01828018, LengthOfArray(meshlist_01828238), LengthOfArray(matlist_01828018),{ -0.334996f, -0.039835f, 13.65316f }, 15.07127f, NULL };

NJS_OBJECT object_01828564 = { NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_01828538, 0, 11.11258f, -0.867072f, 0xFFFFFCBE, 0, 0, 1, 1, 1, NULL, NULL };


NJS_MATERIAL matlist_01828598[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 12, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_FLAG_USE_ENV | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 32, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 48, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 83, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, 20, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFF4D4948 },{ 0xFFFFFFFF }, 11, 14, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_01828610[] = {
	0x8000u | 5, 4, 2, 0, 12, 10,
	0x8000u | 5, 10, 8, 0, 6, 4,
	14, 7, 6, 5, 4, 3, 2, 1, 12, 11, 10, 9, 8, 7, 6
};

Sint16 poly_01828648[] = {
	4, 24, 28, 23, 27,
	4, 26, 24, 25, 23,
	4, 28, 26, 27, 25
};

Sint16 poly_01828668[] = {
	0x8000u | 5, 14, 22, 16, 20, 18,
	0x8000u | 5, 17, 19, 15, 21, 13
};

Sint16 poly_01828680[] = {
	4, 22, 20, 21, 19,
	4, 20, 18, 19, 17,
	4, 16, 14, 15, 13,
	4, 18, 16, 17, 15,
	4, 14, 22, 13, 21
};

Sint16 poly_018286B4[] = {
	0x8000u | 8, 31, 35, 32, 36, 29, 33, 30, 34
};

Sint16 poly_018286C8[] = {
	4, 35, 36, 34, 33,
	4, 30, 29, 31, 32
};

NJS_TEX uv_018286E0[] = {
	{ 163, 210 },
	{ 199, 149 },
	{ 126, 149 },
	{ 163, 88 },
	{ 89, 88 },
	{ 89, 88 },
	{ 53, 149 },
	{ 126, 149 },
	{ 89, 210 },
	{ 163, 210 },
	{ 0, 149 },
	{ 89, 210 },
	{ 63, 254 },
	{ 163, 210 },
	{ 189, 254 },
	{ 199, 149 },
	{ 253, 149 },
	{ 163, 88 },
	{ 189, 43 },
	{ 89, 88 },
	{ 63, 43 },
	{ 53, 149 },
	{ 0, 149 },
	{ 89, 210 }
};

NJS_TEX uv_01828740[] = {
	{ 0, 255 },
	{ 0, 15 },
	{ 5100, 255 },
	{ 5100, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 5100, 255 },
	{ 5100, 15 },
	{ 0, 255 },
	{ 0, 15 },
	{ 5100, 255 },
	{ 5100, 15 }
};

NJS_TEX uv_01828770[] = {
	{ 0, 222 },
	{ 249, 221 },
	{ 3, 53 },
	{ 253, 54 },
	{ 133, -1 },
	{ 133, 12 },
	{ 245, 56 },
	{ 8, 56 },
	{ 244, 220 },
	{ 7, 218 }
};

NJS_TEX uv_01828798[] = {
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 },
	{ 0, 3 },
	{ 251, 3 },
	{ 0, 255 },
	{ 251, 255 }
};

NJS_TEX uv_018287E8[] = {
	{ 247, -1275 },
	{ 0, -1275 },
	{ 247, -688 },
	{ 0, -688 },
	{ 247, -439 },
	{ 0, -439 },
	{ 247, 255 },
	{ 0, 255 }
};

NJS_TEX uv_01828808[] = {
	{ 0, 254 },
	{ 0, 28 },
	{ 253, 254 },
	{ 128, 1 },
	{ 253, 254 },
	{ 128, 1 },
	{ 0, 254 },
	{ 0, 28 }
};

NJS_MESHSET_SADX meshlist_01828828[] = {
	{ NJD_MESHSET_TRIMESH | 0, 3, poly_01828610, NULL, NULL, NULL, uv_018286E0, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 3, poly_01828648, NULL, NULL, NULL, uv_01828740, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_01828668, NULL, NULL, NULL, uv_01828770, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 5, poly_01828680, NULL, NULL, NULL, uv_01828798, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 1, poly_018286B4, NULL, NULL, NULL, uv_018287E8, NULL },
	{ NJD_MESHSET_TRIMESH | 5, 2, poly_018286C8, NULL, NULL, NULL, uv_01828808, NULL }
};

NJS_VECTOR vertex_018288D0[] = {
	{ 0, 0.828626f, -0.263483f },
	{ 1.486466f, 0.01394f, -0.263483f },
	{ 0.858212f, 0.610332f, -0.263483f },
	{ 0.743233f, 0.01394f, -1.550801f },
	{ 0.429106f, 0.610332f, -1.006716f },
	{ -0.743233f, 0.01394f, -1.5508f },
	{ -0.429106f, 0.610332f, -1.006716f },
	{ -1.486466f, 0.01394f, -0.263483f },
	{ -0.858212f, 0.610332f, -0.263483f },
	{ -0.743233f, 0.01394f, 1.023834f },
	{ -0.429106f, 0.610332f, 0.47975f },
	{ 0.743233f, 0.01394f, 1.023834f },
	{ 0.429106f, 0.610332f, 0.47975f },
	{ -0.836994f, 9.123271f, -1.106837f },
	{ -0.891397f, 9.769961f, -1.154505f },
	{ -0.83034f, 9.123271f, 0.838524f },
	{ -0.868009f, 9.769961f, 0.869377f },
	{ 0.024349f, 9.123271f, 1.366645f },
	{ 0.028606f, 9.769961f, 1.528495f },
	{ 0.793967f, 9.123271f, 0.833752f },
	{ 0.846949f, 9.769961f, 0.856082f },
	{ 0.785781f, 9.123271f, -1.131165f },
	{ 0.821567f, 9.769961f, -1.15374f },
	{ 0.007017f, 0.595133f, 0.048774f },
	{ 0.007017f, 9.142028f, 0.048774f },
	{ 0.277883f, 0.595133f, -0.44469f },
	{ 0.277883f, 9.151853f, -0.44469f },
	{ -0.284902f, 0.595133f, -0.432535f },
	{ -0.284902f, 9.151853f, -0.432535f },
	{ -0.7f, 11.31025f, -0.358304f },
	{ -0.7f, 9.773953f, 0.185589f },
	{ -0.7f, 9.773953f, -0.918194f },
	{ -0.7f, 11.15022f, -0.918194f },
	{ 0.7f, 11.31025f, -0.358304f },
	{ 0.7f, 9.773953f, 0.185589f },
	{ 0.7f, 9.773953f, -0.918194f },
	{ 0.7f, 11.15022f, -0.918194f }
};

NJS_VECTOR normal_01828A90[] = {
	{ 0, 1, 0 },
	{ 0.688477f, 0.725259f, 0 },
	{ 0.5418f, 0.840507f, 0 },
	{ 0.344238f, 0.725258f, -0.596238f },
	{ 0.2709f, 0.840507f, -0.469213f },
	{ -0.344238f, 0.725258f, -0.596238f },
	{ -0.2709f, 0.840507f, -0.469213f },
	{ -0.688477f, 0.725258f, 0 },
	{ -0.5418f, 0.840507f, 0 },
	{ -0.344238f, 0.725258f, 0.596238f },
	{ -0.2709f, 0.840507f, 0.469213f },
	{ 0.344238f, 0.725258f, 0.596238f },
	{ 0.2709f, 0.840507f, 0.469213f },
	{ -0.561948f, -0.612224f, -0.556234f },
	{ -0.600251f, 0.54306f, -0.587183f },
	{ -0.657467f, -0.670106f, 0.344521f },
	{ -0.730864f, 0.559411f, 0.39102f },
	{ 0.024531f, -0.667413f, 0.744284f },
	{ 0.027893f, 0.530185f, 0.847423f },
	{ 0.690185f, -0.638575f, 0.340392f },
	{ 0.71938f, 0.598724f, 0.352166f },
	{ 0.551079f, -0.612806f, -0.566375f },
	{ 0.594559f, 0.540965f, -0.594858f },
	{ 0.021593f, 0, 0.999767f },
	{ 0.021593f, 0, 0.999767f },
	{ 0.855027f, 0, -0.518584f },
	{ 0.849969f, 0, -0.526832f },
	{ -0.87662f, 0, -0.481183f },
	{ -0.871924f, 0, -0.489642f },
	{ -0.580673f, 0.723608f, 0.373109f },
	{ -0.616687f, 0.262717f, 0.742077f },
	{ -0.707107f, 0, -0.707107f },
	{ -0.59342f, 0.48467f, -0.64261f },
	{ 0.580673f, 0.723608f, 0.373109f },
	{ 0.616687f, 0.262717f, 0.742077f },
	{ 0.707107f, 0, -0.707107f },
	{ 0.59342f, 0.48467f, -0.64261f }
};

NJS_MODEL_SADX attach_01828C4C = { vertex_018288D0, normal_01828A90, LengthOfArray(vertex_018288D0), meshlist_01828828, matlist_01828598, LengthOfArray(meshlist_01828828), LengthOfArray(matlist_01828598),{ 0, 5.662093f, -0.011153f }, 5.854242f, NULL };

NJS_OBJECT object_01828C78 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL, &attach_01828C4C, 0, 0, 0, 0, 0, 0, 1, 1, 1, &object_01828564, NULL };

//Gachapon thrower


NJS_MATERIAL matlist_001CD844[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64grip, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm32yelvv, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64blin, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_001CD880[] = {
	4, 2, 3, 1, 0
};

Sint16 poly_001CD88A[] = {
	6, 6, 7, 5, 4, 1, 2
};

Sint16 poly_001CD898[] = {
	6, 7, 9, 4, 8, 2, 3,
	6, 1, 0, 5, 10, 6, 11
};

NJS_TEX uv_001CD8B4[] = {
	{ 0, 255 },
	{ 0, -255 },
	{ 510, 255 },
	{ 510, -255 }
};

NJS_TEX uv_001CD8C4[] = {
	{ 765, 0 },
	{ 765, 255 },
	{ 488, 0 },
	{ 488, 255 },
	{ 0 },
	{ 0, 255 }
};

NJS_TEX uv_001CD8DC[] = {
	{ 155, 216 },
	{ 154, 255 },
	{ 115, 145 },
	{ 1, 162 },
	{ 255, 0 },
	{ 0, 113 },
	{ 255, 0 },
	{ 0, 113 },
	{ 115, 145 },
	{ 1, 162 },
	{ 155, 216 },
	{ 154, 255 }
};

NJS_MESHSET_SADX meshlist_001CD90C[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_001CD880, NULL, NULL, NULL, uv_001CD8B4, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 1, poly_001CD88A, NULL, NULL, NULL, uv_001CD8C4, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_001CD898, NULL, NULL, NULL, uv_001CD8DC, NULL }
};

NJS_VECTOR vertex_001CD954[] = {
	{ -4.313202f, -2.516765f, 1.507611f },
	{ 1.864863f, -2.516765f, 4.178239f },
	{ 1.864863f, 1.083235f, 4.178239f },
	{ -4.313202f, 1.083235f, 1.507611f },
	{ -1.510323f, 1.083235f, 0.770041f },
	{ -1.510323f, -2.516765f, 0.770041f },
	{ -0.5352769f, -2.516765f, -0.909511f },
	{ -0.5352769f, 1.083235f, -0.909511f },
	{ -4.270549f, 1.083235f, 0.367385f },
	{ -0.560231f, 1.083235f, -1.815456f },
	{ -4.270549f, -2.516765f, 0.367385f },
	{ -0.560231f, -2.516765f, -1.815456f }
};

NJS_VECTOR normal_001CD9E4[] = {
	{ -0.24958f, -0.7774079f, 0.5773619f },
	{ 0.695403f, -0.53936f, 0.474874f },
	{ 0.695403f, 0.53936f, 0.474874f },
	{ -0.24958f, 0.7774079f, 0.5773619f },
	{ 0.485217f, 0.872187f, -0.06209f },
	{ 0.485217f, -0.872187f, -0.06209f },
	{ 0.448716f, -0.854865f, 0.260498f },
	{ 0.448716f, 0.854865f, 0.260498f },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, -1, 0 },
	{ 0, -1, 0 }
};

NJS_MODEL_SADX attach_001CDA74 = { vertex_001CD954, normal_001CD9E4, LengthOfArray(vertex_001CD954), meshlist_001CD90C, matlist_001CD844, LengthOfArray(meshlist_001CD90C), LengthOfArray(matlist_001CD844),{ -1.22417f, -0.716765f, 1.181392f }, 4.30386f, NULL };

NJS_OBJECT object_001CDA9C = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_001CDA74, -7.56f, 0, 5.399999f, 0, 0, 0, 1, 1, 1, NULL, NULL };

NJS_MATERIAL matlist_001CDAD0[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64grip, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm32yelvv, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64blin, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_001CDB0C[] = {
	4, 1, 0, 2, 3
};

Sint16 poly_001CDB16[] = {
	6, 7, 6, 4, 5, 2, 1
};

Sint16 poly_001CDB24[] = {
	6, 9, 7, 8, 4, 3, 2,
	6, 6, 11, 5, 10, 1, 0
};

NJS_TEX uv_001CDB40[] = {
	{ 0, 255 },
	{ 0, -255 },
	{ 510, 255 },
	{ 510, -255 }
};

NJS_TEX uv_001CDB50[] = {
	{ 0, 255 },
	{ 0 },
	{ 92, 255 },
	{ 92, 0 },
	{ 255, 255 },
	{ 255, 0 }
};

NJS_TEX uv_001CDB68[] = {
	{ 100, 255 },
	{ 99, 216 },
	{ 253, 162 },
	{ 139, 145 },
	{ 255, 113 },
	{ 0 },
	{ 99, 216 },
	{ 100, 255 },
	{ 139, 145 },
	{ 253, 162 },
	{ 0 },
	{ 255, 113 }
};

NJS_MESHSET_SADX meshlist_001CDB98[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_001CDB0C, NULL, NULL, NULL, uv_001CDB40, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 1, poly_001CDB16, NULL, NULL, NULL, uv_001CDB50, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_001CDB24, NULL, NULL, NULL, uv_001CDB68, NULL }
};

NJS_VECTOR vertex_001CDBE0[] = {
	{ 4.313201f, -2.516765f, 1.507612f },
	{ -1.864863f, -2.516765f, 4.178238f },
	{ -1.864863f, 1.083235f, 4.178238f },
	{ 4.313201f, 1.083235f, 1.507612f },
	{ 1.510323f, 1.083235f, 0.770041f },
	{ 1.510323f, -2.516765f, 0.770041f },
	{ 0.5352769f, -2.516765f, -0.909511f },
	{ 0.5352769f, 1.083235f, -0.909511f },
	{ 4.270549f, 1.083235f, 0.367386f },
	{ 0.560232f, 1.083235f, -1.815456f },
	{ 4.270549f, -2.516765f, 0.367386f },
	{ 0.560232f, -2.516765f, -1.815456f }
};

NJS_VECTOR normal_001CDC70[] = {
	{ 0.24958f, -0.7774079f, 0.5773619f },
	{ -0.695403f, -0.53936f, 0.474874f },
	{ -0.695403f, 0.53936f, 0.474874f },
	{ 0.24958f, 0.7774079f, 0.5773619f },
	{ -0.485217f, 0.872187f, -0.06209f },
	{ -0.485217f, -0.872187f, -0.06209f },
	{ -0.448717f, -0.854865f, 0.260498f },
	{ -0.448717f, 0.854865f, 0.260498f },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, -1, 0 },
	{ 0, -1, 0 }
};

NJS_MODEL_SADX attach_001CDD00 = { vertex_001CDBE0, normal_001CDC70, LengthOfArray(vertex_001CDBE0), meshlist_001CDB98, matlist_001CDAD0, LengthOfArray(meshlist_001CDB98), LengthOfArray(matlist_001CDAD0),{ 1.224169f, -0.716765f, 1.181391f }, 4.30386f, NULL };

NJS_OBJECT object_001CDD28 = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_001CDD00, 7.56f, 0, 5.399999f, 0, 0, 0, 1, 1, 1, NULL, &object_001CDA9C };

NJS_MATERIAL matlist_001CDD5C[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm32bk1, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFF000000 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm128tec, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_FLAG_USE_ENV | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFF383836 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm128tec, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_FLAG_USE_ENV | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm32bk1, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64xxx, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_001CDDC0[] = {
	0x8000u | 8, 12, 14, 10, 0, 8, 2, 6, 4
};

Sint16 poly_001CDDD2[] = {
	4, 7, 5, 6, 4,
	8, 6, 8, 7, 9, 5, 3, 4, 2
};

Sint16 poly_001CDDEE[] = {
	8, 14, 0, 15, 1, 13, 11, 12, 10,
	4, 15, 13, 14, 12
};

Sint16 poly_001CDE0A[] = {
	4, 11, 9, 10, 8,
	4, 3, 1, 2, 0
};

Sint16 poly_001CDE1E[] = {
	4, 1, 3, 11, 9
};

NJS_TEX uv_001CDE28[] = {
	{ 225, 255 },
	{ 541, 252 },
	{ 0, -489 },
	{ 765, -495 },
	{ 0, -1544 },
	{ 764, -1550 },
	{ 223, -2292 },
	{ 539, -2295 }
};

NJS_TEX uv_001CDE48[] = {
	{ 98, 150 },
	{ 156, 150 },
	{ 74, 0 },
	{ 180, 0 },
	{ 74, 0 },
	{ 0, 193 },
	{ 98, 150 },
	{ 58, 255 },
	{ 156, 150 },
	{ 196, 254 },
	{ 180, 0 },
	{ 255, 191 }
};

NJS_TEX uv_001CDE78[] = {
	{ 180, 254 },
	{ 255, 61 },
	{ 156, 104 },
	{ 196, 0 },
	{ 98, 104 },
	{ 58, 0 },
	{ 74, 254 },
	{ 0, 63 },
	{ 156, 104 },
	{ 98, 104 },
	{ 180, 254 },
	{ 74, 254 }
};

NJS_TEX uv_001CDEA8[] = {
	{ 0 },
	{ 255, 0 },
	{ 0, 255 },
	{ 255, 255 },
	{ 0 },
	{ 255, 0 },
	{ 0, 255 },
	{ 255, 255 }
};

NJS_TEX uv_001CDEC8[] = {
	{ 510, 253 },
	{ 509, 0 },
	{ 0, 255 },
	{ 0, 1 }
};

NJS_MESHSET_SADX meshlist_001CDED8[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_001CDDC0, NULL, NULL, NULL, uv_001CDE28, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 2, poly_001CDDD2, NULL, NULL, NULL, uv_001CDE48, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 2, poly_001CDDEE, NULL, NULL, NULL, uv_001CDE78, NULL },
	{ NJD_MESHSET_TRIMESH | 3, 2, poly_001CDE0A, NULL, NULL, NULL, uv_001CDEA8, NULL },
	{ NJD_MESHSET_TRIMESH | 4, 1, poly_001CDE1E, NULL, NULL, NULL, uv_001CDEC8, NULL }
};

NJS_VECTOR vertex_001CDF50[] = {
	{ 8.148665f, -11.78558f, -0.042384f },
	{ 4.367885f, -10.23147f, 3.168569f },
	{ 8.13026f, -4.966535f, -0.042386f },
	{ 4.357924f, -6.541029f, 3.168569f },
	{ 3.295455f, -0.157755f, -0.042384f },
	{ 1.741346f, -3.938538f, 3.16857f },
	{ -3.52359f, -0.17616f, -0.042385f },
	{ -1.949096f, -3.948498f, 3.168571f },
	{ -8.332371f, -5.010969f, -0.042384f },
	{ -4.551589f, -6.565077f, 3.16857f },
	{ -8.313966f, -11.83001f, -0.042383f },
	{ -4.541627f, -10.25552f, 3.16857f },
	{ -3.479158f, -16.63878f, -0.042384f },
	{ -1.925048f, -12.85801f, 3.16857f },
	{ 3.339887f, -16.62038f, -0.042385f },
	{ 1.765392f, -12.84805f, 3.168569f }
};

NJS_VECTOR normal_001CE010[] = {
	{ 0.889956f, -0.365821f, -0.272311f },
	{ 0.365819f, -0.150372f, 0.918458f },
	{ 0.8879679f, 0.370619f, -0.272311f },
	{ 0.365003f, 0.152344f, 0.918458f },
	{ 0.365821f, 0.889956f, -0.272311f },
	{ 0.150372f, 0.365819f, 0.918458f },
	{ -0.37062f, 0.8879679f, -0.272311f },
	{ -0.152344f, 0.365002f, 0.918458f },
	{ -0.889956f, 0.365821f, -0.272311f },
	{ -0.365819f, 0.150372f, 0.918458f },
	{ -0.8879679f, -0.37062f, -0.272311f },
	{ -0.365002f, -0.152345f, 0.918458f },
	{ -0.365821f, -0.889956f, -0.272312f },
	{ -0.150372f, -0.36582f, 0.918457f },
	{ 0.370619f, -0.8879679f, -0.272311f },
	{ 0.152344f, -0.365003f, 0.918458f }
};

NJS_MODEL_SADX attach_001CE0D0 = { vertex_001CDF50, normal_001CE010, LengthOfArray(vertex_001CDF50), meshlist_001CDED8, matlist_001CDD5C, LengthOfArray(meshlist_001CDED8), LengthOfArray(matlist_001CDD5C),{ -0.09185199f, -8.398268f, 1.563092f }, 8.395456f, NULL };

NJS_OBJECT object_001CE0F8 = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_001CE0D0, 0, 7.713189f, 6.229787f, 0, 0, 0, 1, 1, 1, NULL, &object_001CDD28 };

NJS_MATERIAL matlist_001CE12C[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64bkgg, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_fq64wall17, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, OBJ_FINALEGGTexName_tm64bk1, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_001CE168[] = {
	0x8000u | 8, 1, 9, 0, 8, 7, 15, 6, 14,
	0x8000u | 12, 9, 1, 10, 2, 11, 3, 12, 4, 13, 5, 14, 6
};

Sint16 poly_001CE194[] = {
	0x8000u | 8, 22, 21, 23, 20, 16, 19, 17, 18
};

Sint16 poly_001CE1A6[] = {
	4, 16, 23, 0, 7,
	4, 17, 16, 1, 0,
	4, 18, 17, 2, 1,
	4, 19, 18, 3, 2,
	4, 20, 19, 4, 3,
	4, 21, 20, 5, 4,
	4, 22, 21, 6, 5,
	4, 23, 22, 7, 6
};

NJS_TEX uv_001CE1F8[] = {
	{ 0, 255 },
	{ 255, 255 },
	{ 0, -169 },
	{ 255, -169 },
	{ 0, -594 },
	{ 255, -594 },
	{ 0, -1020 },
	{ 255, -1020 },
	{ 255, -1785 },
	{ 0, -1785 },
	{ 255, -1377 },
	{ 0, -1377 },
	{ 255, -969 },
	{ 0, -969 },
	{ 255, -561 },
	{ 0, -561 },
	{ 255, -152 },
	{ 0, -152 },
	{ 255, 255 },
	{ 0, 255 }
};

NJS_TEX uv_001CE248[] = {
	{ 173, 233 },
	{ 82, 233 },
	{ 237, 170 },
	{ 18, 170 },
	{ 236, 81 },
	{ 18, 81 },
	{ 172, 18 },
	{ 82, 18 }
};

NJS_TEX uv_001CE268[] = {
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 },
	{ 0 },
	{ 510, 0 },
	{ 0, 255 },
	{ 510, 255 }
};

NJS_MESHSET_SADX meshlist_001CE2E8[] = {
	{ NJD_MESHSET_TRIMESH | 0, 2, poly_001CE168, NULL, NULL, NULL, uv_001CE1F8, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 1, poly_001CE194, NULL, NULL, NULL, uv_001CE248, NULL },
	{ NJD_MESHSET_TRIMESH | 2, 8, poly_001CE1A6, NULL, NULL, NULL, uv_001CE268, NULL }
};

NJS_VECTOR vertex_001CE330[] = {
	{ 8.13026f, 2.770392f, 6.18396f },
	{ 3.295456f, 7.579172f, 6.183961f },
	{ -3.523592f, 7.560769f, 6.183961f },
	{ -8.332372f, 2.72596f, 6.18396f },
	{ -8.313965f, -4.093085f, 6.18396f },
	{ -3.479157f, -8.901873f, 6.18396f },
	{ 3.339887f, -8.883468f, 6.18396f },
	{ 8.148668f, -4.048652f, 6.183961f },
	{ 8.130261f, 2.770392f, 0.063963f },
	{ 3.295457f, 7.579172f, 0.063963f },
	{ -3.52359f, 7.560769f, 0.063963f },
	{ -8.332371f, 2.72596f, 0.063961f },
	{ -8.313966f, -4.093085f, 0.063963f },
	{ -3.479158f, -8.901873f, 0.063961f },
	{ 3.339888f, -8.883468f, 0.063961f },
	{ 8.148665f, -4.048652f, 0.063963f },
	{ 5.580613f, 1.872342f, 3.66396f },
	{ 2.262004f, 5.122308f, 3.66396f },
	{ -2.418591f, 5.10987f, 3.66396f },
	{ -5.719344f, 1.842313f, 3.66396f },
	{ -5.70671f, -2.766269f, 3.66396f },
	{ -2.388097f, -6.016239f, 3.66396f },
	{ 2.292498f, -6.003795f, 3.663959f },
	{ 5.593246f, -2.736241f, 3.663961f }
};

NJS_VECTOR normal_001CE450[] = {
	{ 0.51164f, 0.220294f, 0.830479f },
	{ 0.210903f, 0.51193f, 0.8327349f },
	{ -0.210649f, 0.51289f, 0.832208f },
	{ -0.515617f, 0.218031f, 0.828614f },
	{ -0.5290779f, -0.212478f, 0.821541f },
	{ -0.223353f, -0.532957f, 0.816131f },
	{ 0.226191f, -0.529882f, 0.817351f },
	{ 0.52767f, -0.205971f, 0.8240989f },
	{ 0.922843f, 0.385175f, 0 },
	{ 0.380189f, 0.924909f, 0 },
	{ -0.385175f, 0.922843f, 0 },
	{ -0.924909f, 0.380188f, 0 },
	{ -0.922843f, -0.385175f, 0 },
	{ -0.380189f, -0.924909f, 0 },
	{ 0.385176f, -0.922843f, 0 },
	{ 0.924909f, -0.380188f, 0 },
	{ -0.402697f, -0.174907f, 0.8984669f },
	{ -0.166651f, -0.41038f, 0.896558f },
	{ 0.167684f, -0.410198f, 0.896448f },
	{ 0.400584f, -0.173179f, 0.899745f },
	{ 0.389963f, 0.154305f, 0.90781f },
	{ 0.155945f, 0.373961f, 0.9142399f },
	{ -0.161991f, 0.375927f, 0.91238f },
	{ -0.397394f, 0.154607f, 0.90453f }
};

NJS_MODEL_SADX attach_001CE570 = { vertex_001CE330, normal_001CE450, LengthOfArray(vertex_001CE330), meshlist_001CE2E8, matlist_001CE12C, LengthOfArray(meshlist_001CE2E8), LengthOfArray(matlist_001CE12C),{ -0.091851f, -0.66135f, 3.123961f }, 8.790324f, NULL };

NJS_OBJECT object_001CE598 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL, &attach_001CE570, 0, 0, 0, 0, 0, 0, 1, 1, 1, &object_001CE0F8, NULL };
