#include "stdafx.h"
#include "SADXModLoader.h"
/* NINJA Basic (with Sonic Adventure DX additions) model
*
* Generated by SAMDL
*
* Description: ___ADV01C_OBJECTS[7]
*
*/

enum EC_TARAITexName
{
	EC_TARAITexName_edc_k_jmedama,
	EC_TARAITexName_edv_k_traingarasu,
	EC_TARAITexName_edv_f_kagayab,
	EC_TARAITexName_edv_f_mojia,
	EC_TARAITexName_ecf_funa,
	EC_TARAITexName_edv_f_nana,
	EC_TARAITexName_era_s_intb,
	EC_TARAITexName_k_tuekabe,
	EC_TARAITexName_edv_f_wee,
	EC_TARAITexName_edv_f_good,
	EC_TARAITexName_edc_f_kemuri,
	EC_TARAITexName_mr_032o_kasan,
	EC_TARAITexName_edb_f_taraib,
	EC_TARAITexName_edv_f_kagaya,
	EC_TARAITexName_edv_f_mojie,
	EC_TARAITexName_edv_f_mojig,
	EC_TARAITexName_edv_f_mojim,
	EC_TARAITexName_edv_f_mojin
};

NJS_MATERIAL matlist_00111440[] = {
	{ { 0x7FB2B2B2 },{ 0xFFFFFFFF }, 11, EC_TARAITexName_edv_f_mojia, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00111454[] = {
	4, 3, 2, 1, 0
};

NJS_TEX uv_00111460[] = {
	{ 255, 0 },
	{ 255, 254 },
	{ 0 },
	{ 0, 254 }
};

NJS_MESHSET_SADX meshlist_00111470[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_00111454, NULL, NULL, NULL, uv_00111460, NULL }
};

NJS_VECTOR vertex_0011148C[] = {
	{ -6.639945f, 0, -6.457226f },
	{ -6.639945f, 0, 6.822663f },
	{ 6.639945f, 0, -6.457226f },
	{ 6.639945f, 0, 6.822663f }
};

NJS_VECTOR normal_001114BC[] = {
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 }
};

NJS_MODEL_SADX attach_001114EC = { vertex_0011148C, normal_001114BC, LengthOfArray(vertex_0011148C), meshlist_00111470, matlist_00111440, LengthOfArray(meshlist_00111470), LengthOfArray(matlist_00111440),{ 0, 0, 0.182719f }, 9.390301f, NULL };

NJS_OBJECT object_00111518 = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_001114EC, 0, 2.028263f, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

NJS_MATERIAL matlist_0011154C[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, EC_TARAITexName_edv_f_kagayab, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, EC_TARAITexName_edv_k_traingarasu, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_IGNORE_LIGHT | NJD_FLAG_USE_TEXTURE | NJD_FLAG_USE_ENV | NJD_DA_INV_SRC | NJD_SA_SRC },
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, EC_TARAITexName_edc_k_jmedama, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_FLAG_USE_ALPHA | NJD_FLAG_IGNORE_LIGHT | NJD_DA_INV_SRC | NJD_SA_SRC }
};

NJS_MATERIAL matlist_0011154CZ[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, EC_TARAITexName_edv_f_kagayab, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_IGNORE_LIGHT | NJD_DA_ONE | NJD_SA_SRC },
};

Sint16 poly_00111588[] = {
	4, 4, 10, 11, 9,
	0x8000u | 8, 4, 10, 3, 8, 2, 6, 5, 7,
	0x8000u | 7, 11, 4, 0, 3, 1, 2, 5,
	5, 6, 7, 8, 9, 10
};

Sint16 poly_001115C0[] = {
	0x8000u | 6, 21, 19, 23, 17, 14, 15
};

Sint16 poly_001115D0[] = {
	0x8000u | 14, 14, 13, 23, 22, 21, 20, 19, 18, 17, 16, 15, 12, 14, 13
};

NJS_TEX uv_001115F0[] = {
	{ 382, 255 },
	{ 127, 255 },
	{ 382, 255 },
	{ 127, 255 },
	{ 382, -255 },
	{ 127, -255 },
	{ 510, 0 },
	{ 0 },
	{ 382, 254 },
	{ 127, 254 },
	{ 127, 254 },
	{ 0 },
	{ 382, -255 },
	{ 382, -255 },
	{ 510, 0 },
	{ 510, 0 },
	{ 382, 254 },
	{ 382, 254 },
	{ 127, 254 },
	{ 127, 254 },
	{ 0 },
	{ 0 },
	{ 127, -255 },
	{ 127, -255 }
};

NJS_TEX uv_00111650[] = {
	{ 63, 0 },
	{ 0, 127 },
	{ 191, 0 },
	{ 63, 254 },
	{ 255, 127 },
	{ 191, 254 }
};

NJS_TEX uv_00111668[] = {
	{ 3315, 0 },
	{ 3315, 255 },
	{ 2805, 0 },
	{ 2805, 255 },
	{ 2295, 0 },
	{ 2295, 255 },
	{ 1785, 0 },
	{ 1785, 255 },
	{ 1275, 0 },
	{ 1275, 255 },
	{ 765, 0 },
	{ 765, 255 },
	{ 255, 0 },
	{ 255, 255 }
};

NJS_MESHSET_SADX meshlist_001116A0[] = {
	{ NJD_MESHSET_TRIMESH | 2, 1, poly_001115D0, NULL, NULL, NULL, uv_00111668, NULL },
	{ NJD_MESHSET_TRIMESH | 1, 1, poly_001115C0, NULL, NULL, NULL, uv_00111650, NULL },
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00111588, NULL, NULL, NULL, uv_001115F0, NULL },
};

NJS_MESHSET_SADX meshlist_001116A0Z[] = {
	{ NJD_MESHSET_TRIMESH | 0, 4, poly_00111588, NULL, NULL, NULL, uv_001115F0, NULL }
};

NJS_VECTOR vertex_001116F8[] = {
	{ 11.2f, 1.217862f, 0 },
	{ 5.599999f, 1.217862f, -9.699486f },
	{ 5.599999f, 2.925f, -9.699486f },
	{ 11.2f, 2.925f, 0 },
	{ 5.600003f, 2.925f, 9.699486f },
	{ -5.600001f, 1.217862f, -9.699484f },
	{ -5.600001f, 2.925f, -9.699484f },
	{ -11.2f, 1.217862f, 0 },
	{ -11.2f, 2.925f, 0 },
	{ -5.599998f, 1.217862f, 9.699486f },
	{ -5.599998f, 2.925f, 9.699486f },
	{ 5.600003f, 1.217862f, 9.699486f },
	{ 5.6f, -2.925f, -9.69949f },
	{ 11.2f, -2.925f, 0 },
	{ 11.2f, 1.217862f, 0 },
	{ 5.599999f, 1.217862f, -9.699486f },
	{ -5.600001f, -2.925f, -9.699484f },
	{ -5.600001f, 1.217862f, -9.699484f },
	{ -11.2f, -2.925f, 0 },
	{ -11.2f, 1.217862f, 0 },
	{ -5.599998f, -2.925f, 9.699486f },
	{ -5.599998f, 1.217862f, 9.699486f },
	{ 5.600003f, -2.925f, 9.699486f },
	{ 5.600003f, 1.217862f, 9.699486f }
};

NJS_VECTOR normal_00111818[] = {
	{ 1, 0, 0 },
	{ 0.5f, 0, -0.866025f },
	{ 0.396203f, 0.609994f, -0.686244f },
	{ 0.792406f, 0.609994f, 0 },
	{ 0.396203f, 0.609994f, 0.686243f },
	{ -0.5f, 0, -0.866025f },
	{ -0.396203f, 0.609994f, -0.686244f },
	{ -1, 0, 0 },
	{ -0.792406f, 0.609994f, 0 },
	{ -0.5f, 0, 0.866025f },
	{ -0.396203f, 0.609994f, 0.686244f },
	{ 0.5f, 0, 0.866025f },
	{ 0.5f, 0.000001f, -0.866026f },
	{ 1, 0, 0 },
	{ 0.792406f, 0.609994f, 0 },
	{ 0.396203f, 0.609994f, -0.686243f },
	{ -0.5f, 0.000001f, -0.866025f },
	{ -0.396203f, 0.609995f, -0.686243f },
	{ -1, 0, 0 },
	{ -0.792406f, 0.609994f, 0 },
	{ -0.5f, 0, 0.866025f },
	{ -0.396203f, 0.609994f, 0.686244f },
	{ 0.5f, 0, 0.866025f },
	{ 0.396203f, 0.609994f, 0.686243f }
};

NJS_MODEL_SADX attach_00111938 = { vertex_001116F8, normal_00111818, LengthOfArray(vertex_001116F8), meshlist_001116A0, matlist_0011154C, LengthOfArray(meshlist_001116A0), LengthOfArray(matlist_0011154C),{ 0, 0, -0.00002f }, 14.81621f, NULL };

NJS_OBJECT object_00111964 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL, &attach_00111938, 0, 0, 0, 0, 0, 0, 1, 1, 1, &object_00111518, NULL };

NJS_MODEL_SADX attach_00111938Z = { vertex_001116F8, normal_00111818, LengthOfArray(vertex_001116F8), meshlist_001116A0Z, matlist_0011154CZ, LengthOfArray(meshlist_001116A0Z), LengthOfArray(matlist_0011154CZ),{ 0, 0, -0.00002f }, 14.81621f, NULL };

NJS_OBJECT object_00111964Z = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL, &attach_00111938Z, 0, -2.028263f, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };
